<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Banks as Information Producers – Banking</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Notes/06_chapter6_liquidity_provision.html" rel="next">
<link href="../Notes/04_chapter4_supplement.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Notes/01_chapter1_what_is_a_bank.html">Fundamentals of Banking</a></li><li class="breadcrumb-item"><a href="../Notes/05_chapter5_information_producers.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Banks as Information Producers</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Banking</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Fundamentals of Banking</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/01_chapter1_what_is_a_bank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">The Economic Role of Banks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/02_chapter2_liquidity_creation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Liquidity Creation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/03_chapter3_bank_runs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bank Runs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/04_chapter4_supplement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bank Runs and Failures: Supplement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/05_chapter5_information_producers.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Banks as Information Producers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/06_chapter6_liquidity_provision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Deposit-Lending Synergy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Notes/07_chapter7_information_insensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Liquidity Creation Through Information Insensitivity</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#information-intermediation" id="toc-information-intermediation" class="nav-link active" data-scroll-target="#information-intermediation"><span class="header-section-number">5.1</span> Information Intermediation</a></li>
  <li><a href="#ex-ante-banks-as-information-producers" id="toc-ex-ante-banks-as-information-producers" class="nav-link" data-scroll-target="#ex-ante-banks-as-information-producers"><span class="header-section-number">5.2</span> Ex Ante: Banks as Information Producers</a>
  <ul class="collapse">
  <li><a href="#the-adverse-selection-problem" id="toc-the-adverse-selection-problem" class="nav-link" data-scroll-target="#the-adverse-selection-problem"><span class="header-section-number">5.2.1</span> The Adverse Selection Problem</a></li>
  <li><a href="#signaling-leland-and-pyle-1977" id="toc-signaling-leland-and-pyle-1977" class="nav-link" data-scroll-target="#signaling-leland-and-pyle-1977"><span class="header-section-number">5.2.2</span> Signaling: Leland and Pyle (1977)</a></li>
  <li><a href="#banks-as-information-producers-ramakrishnan-and-thakor-1984" id="toc-banks-as-information-producers-ramakrishnan-and-thakor-1984" class="nav-link" data-scroll-target="#banks-as-information-producers-ramakrishnan-and-thakor-1984"><span class="header-section-number">5.2.3</span> Banks as Information Producers: Ramakrishnan and Thakor (1984)</a></li>
  <li><a href="#banks-as-certifiers-fama-1985" id="toc-banks-as-certifiers-fama-1985" class="nav-link" data-scroll-target="#banks-as-certifiers-fama-1985"><span class="header-section-number">5.2.4</span> Banks as Certifiers: Fama (1985)</a></li>
  </ul></li>
  <li><a href="#ex-post-banks-as-delegated-monitors" id="toc-ex-post-banks-as-delegated-monitors" class="nav-link" data-scroll-target="#ex-post-banks-as-delegated-monitors"><span class="header-section-number">5.3</span> Ex Post: Banks as Delegated Monitors</a>
  <ul class="collapse">
  <li><a href="#the-environment" id="toc-the-environment" class="nav-link" data-scroll-target="#the-environment"><span class="header-section-number">5.3.1</span> The Environment</a></li>
  <li><a href="#the-costly-state-verification-framework" id="toc-the-costly-state-verification-framework" class="nav-link" data-scroll-target="#the-costly-state-verification-framework"><span class="header-section-number">5.3.2</span> The Costly State Verification Framework</a></li>
  <li><a href="#unmonitored-debt" id="toc-unmonitored-debt" class="nav-link" data-scroll-target="#unmonitored-debt"><span class="header-section-number">5.3.3</span> Unmonitored Debt</a></li>
  <li><a href="#the-value-of-monitoring" id="toc-the-value-of-monitoring" class="nav-link" data-scroll-target="#the-value-of-monitoring"><span class="header-section-number">5.3.4</span> The Value of Monitoring</a></li>
  <li><a href="#why-direct-monitoring-fails" id="toc-why-direct-monitoring-fails" class="nav-link" data-scroll-target="#why-direct-monitoring-fails"><span class="header-section-number">5.3.5</span> Why Direct Monitoring Fails</a></li>
  <li><a href="#the-bank-as-delegated-monitor" id="toc-the-bank-as-delegated-monitor" class="nav-link" data-scroll-target="#the-bank-as-delegated-monitor"><span class="header-section-number">5.3.6</span> The Bank as Delegated Monitor</a></li>
  <li><a href="#the-one-loan-bank" id="toc-the-one-loan-bank" class="nav-link" data-scroll-target="#the-one-loan-bank"><span class="header-section-number">5.3.7</span> The One-Loan Bank</a></li>
  <li><a href="#the-two-loan-bank" id="toc-the-two-loan-bank" class="nav-link" data-scroll-target="#the-two-loan-bank"><span class="header-section-number">5.3.8</span> The Two-Loan Bank</a></li>
  <li><a href="#three-arrangements-compared" id="toc-three-arrangements-compared" class="nav-link" data-scroll-target="#three-arrangements-compared"><span class="header-section-number">5.3.9</span> Three Arrangements Compared</a></li>
  <li><a href="#the-n-loan-bank" id="toc-the-n-loan-bank" class="nav-link" data-scroll-target="#the-n-loan-bank"><span class="header-section-number">5.3.10</span> The <span class="math inline">\(n\)</span>-Loan Bank</a></li>
  <li><a href="#the-formal-diamond-1984-model" id="toc-the-formal-diamond-1984-model" class="nav-link" data-scroll-target="#the-formal-diamond-1984-model"><span class="header-section-number">5.3.11</span> The Formal Diamond (1984) Model</a></li>
  <li><a href="#what-makes-a-good-bank" id="toc-what-makes-a-good-bank" class="nav-link" data-scroll-target="#what-makes-a-good-bank"><span class="header-section-number">5.3.12</span> What Makes a Good Bank?</a></li>
  <li><a href="#the-asset-and-liability-sides-together" id="toc-the-asset-and-liability-sides-together" class="nav-link" data-scroll-target="#the-asset-and-liability-sides-together"><span class="header-section-number">5.3.13</span> The Asset and Liability Sides Together</a></li>
  <li><a href="#diversification-the-unifying-principle" id="toc-diversification-the-unifying-principle" class="nav-link" data-scroll-target="#diversification-the-unifying-principle"><span class="header-section-number">5.3.14</span> Diversification: The Unifying Principle</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">5.4</span> Key Takeaways</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">5.5</span> References</a>
  <ul class="collapse">
  <li><a href="#primary-sources" id="toc-primary-sources" class="nav-link" data-scroll-target="#primary-sources"><span class="header-section-number">5.5.1</span> Primary Sources</a></li>
  <li><a href="#foundations-debt-and-liquidation" id="toc-foundations-debt-and-liquidation" class="nav-link" data-scroll-target="#foundations-debt-and-liquidation"><span class="header-section-number">5.5.2</span> Foundations: Debt and Liquidation</a></li>
  <li><a href="#extensions" id="toc-extensions" class="nav-link" data-scroll-target="#extensions"><span class="header-section-number">5.5.3</span> Extensions</a></li>
  <li><a href="#integrating-the-liability-and-asset-sides" id="toc-integrating-the-liability-and-asset-sides" class="nav-link" data-scroll-target="#integrating-the-liability-and-asset-sides"><span class="header-section-number">5.5.4</span> Integrating the Liability and Asset Sides</a></li>
  <li><a href="#empirical-relevance" id="toc-empirical-relevance" class="nav-link" data-scroll-target="#empirical-relevance"><span class="header-section-number">5.5.5</span> Empirical Relevance</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Notes/01_chapter1_what_is_a_bank.html">Fundamentals of Banking</a></li><li class="breadcrumb-item"><a href="../Notes/05_chapter5_information_producers.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Banks as Information Producers</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Banks as Information Producers</span></h1>
<p class="subtitle lead">The Asset-Side Role of Banks</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="information-intermediation" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="information-intermediation"><span class="header-section-number">5.1</span> Information Intermediation</h2>
<p>The previous chapters built the <strong>liability-side</strong> justification for banking. In the Diamond-Dybvig model, banks exist because they solve a <strong>liquidity problem</strong>: depositors face uncertainty about when they will need funds, and banks pool this risk by offering liquid deposits backed by illiquid long-term investments. The resulting maturity transformation creates social value — but also fragility.</p>
<p>This chapter pivots to the <strong>asset side</strong> of the balance sheet. Even if there were no liquidity problem, banks might still exist. The reason: <strong>information asymmetry between borrowers and lenders</strong>.</p>
<p>Two broad traditions address this asymmetry, organized around <em>when</em> the information problem arises.</p>
<p><strong>The adverse selection view</strong> focuses on the problem that arises <em>before</em> lending: lenders cannot observe borrower quality, so credit markets may exclude good borrowers (Stiglitz and Weiss 1981) or price loans inefficiently. Two theories explain how banks solve this problem. Leland and Pyle (1977) show that entrepreneurs can signal project quality by retaining equity — skin in the game — and that a bank holding a diversified loan portfolio can perform this certification at vanishing cost as the portfolio grows. Ramakrishnan and Thakor (1984) extend this: a coalition of informed specialists aggregates independent noisy signals, so pooling information production across many loans drives residual uncertainty toward zero. In both stories, banks are <strong>information producers</strong> — they certify borrower quality to outside investors and fund themselves cheaply as a result.</p>
<p><strong>The moral hazard view</strong> focuses on the problem that arises <em>after</em> lending: borrowers can misreport realized returns, and direct lenders cannot monitor numerous small investors per project cheaply. Diamond (1984) shows that a bank can solve this by monitoring on behalf of all depositors — and that the bank’s own incentive to monitor is sustained by the threat of liquidation embedded in its <strong>fixed-rate deposit contract</strong>. The deposit structure is not arbitrary: it is the contract that minimizes delegation costs and makes the bank’s monitoring credible.</p>
<p>This chapter covers both views, but the Diamond (1984) model receives the most attention. The reason is straightforward: it not only explains why banks monitor — it also endogenously generates the <strong>organizational form of the bank</strong> (monitored loans on the asset side, fixed-rate deposits on the liability side). The adverse selection models explain the asset side well, but they do not independently pin down the liability structure. Diamond does both.</p>
<hr>
</section>
<section id="ex-ante-banks-as-information-producers" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="ex-ante-banks-as-information-producers"><span class="header-section-number">5.2</span> Ex Ante: Banks as Information Producers</h2>
<section id="the-adverse-selection-problem" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="the-adverse-selection-problem"><span class="header-section-number">5.2.1</span> The Adverse Selection Problem</h3>
<section id="setup" class="level4" data-number="5.2.1.1">
<h4 data-number="5.2.1.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">5.2.1.1</span> Setup</h4>
<p>We model the adverse selection problem following <strong>Stiglitz and Weiss (1981)</strong>. There is a population of borrowers and a competitive lending market. Each borrower has a project requiring investment <span class="math inline">\(I = 1\)</span>.</p>
<p><strong>Borrower types</strong>: There are two types <span class="math inline">\(\theta \in \{G, B\}\)</span>:</p>
<ul>
<li>A fraction <span class="math inline">\(\alpha\)</span> of borrowers are <strong>type <span class="math inline">\(G\)</span></strong> (good): high probability <span class="math inline">\(p_G\)</span> of success, lower maximum payoff <span class="math inline">\(y_G\)</span> if successful</li>
<li>A fraction <span class="math inline">\(1 - \alpha\)</span> of borrowers are <strong>type <span class="math inline">\(B\)</span></strong> (bad): low probability <span class="math inline">\(p_B\)</span> of success, higher maximum payoff <span class="math inline">\(y_B\)</span> if successful</li>
</ul>
<p>These types satisfy the <strong>mean-preserving spread</strong> condition:</p>
<p><span class="math display">\[p_G &gt; p_B, \quad y_G &lt; y_B, \quad p_G y_G = p_B y_B = \mu\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the common expected project return. The risk-free rate is <span class="math inline">\(r = 1.05\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mean-Preserving Spread and Adverse Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>mean-preserving spread</strong> makes a distribution riskier without changing its mean. Here, type <span class="math inline">\(B\)</span> is a mean-preserving spread of type <span class="math inline">\(G\)</span>: both earn <span class="math inline">\(\mu\)</span> in expectation, but type <span class="math inline">\(B\)</span> reaches it through a high-variance lottery (low <span class="math inline">\(p_B\)</span>, high <span class="math inline">\(y_B\)</span>).</p>
<p>This is what makes adverse selection bite. Because both types look identical in expectation, the lender cannot distinguish them by pricing alone. Raising <span class="math inline">\(f\)</span> screens out <em>good</em> borrowers first — type <span class="math inline">\(G\)</span> exits when <span class="math inline">\(f &gt; y_G\)</span> — while bad borrowers, with their higher upside <span class="math inline">\(y_B &gt; y_G\)</span>, stay. The lender’s only instrument is blunt.</p>
</div>
</div>
<p><strong>Information structure</strong>: The lender observes the project <em>outcome</em> (success paying <span class="math inline">\(y_\theta\)</span>, or failure paying <span class="math inline">\(0\)</span>) but <strong>cannot observe the borrower’s type</strong> <span class="math inline">\(\theta\)</span>. The borrower knows their own type.</p>
<p><strong>Contract</strong>: A standard debt contract specifies a face value <span class="math inline">\(f\)</span>. The borrower repays <span class="math inline">\(f\)</span> if the project succeeds; defaults if it fails (lender receives 0 on failure).</p>
<p><strong>Payoffs</strong>:</p>
<ul>
<li>Borrower of type <span class="math inline">\(\theta\)</span>: <span class="math inline">\(\pi_\theta(f) = p_\theta(y_\theta - f)\)</span></li>
<li>Lender’s expected return from a type <span class="math inline">\(\theta\)</span> loan: <span class="math inline">\(\Pi_\theta(f) = p_\theta f\)</span></li>
</ul>
<p><strong>Type-specific break-even face values</strong>: For the lender to break even on a loan to a known type-<span class="math inline">\(\theta\)</span> borrower:</p>
<p><span class="math display">\[f_\theta^* = \frac{r}{p_\theta}\]</span></p>
<p>Since <span class="math inline">\(p_G &gt; p_B\)</span>, we have <span class="math inline">\(f_G^* &lt; f_B^*\)</span>: good borrowers can be served at a lower face value because their higher success probability makes repayment more likely.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why Does Break-Even Equal the Risk-Free Rate?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The lender is making a risky loan — so why is the break-even condition <span class="math inline">\(p_\theta f = r\)</span> rather than <span class="math inline">\(r\)</span> plus a risk premium?</p>
<p>The model assumes lenders are <strong>risk-neutral</strong> and the market is <strong>competitive</strong>. Risk-neutrality means lenders care only about expected returns, not variance. Competition drives expected profits to zero. Together, these imply the lender’s opportunity cost is simply <span class="math inline">\(r\)</span> — the return available on a safe asset — and any loan that delivers <span class="math inline">\(r\)</span> in expectation is acceptable, regardless of its risk profile.</p>
<p>This is a deliberate modeling choice, not a description of reality. By assuming risk-neutrality, the model isolates the effect of <strong>information asymmetry</strong> alone. If lenders were risk-averse, any excess return above <span class="math inline">\(r\)</span> could be attributed to either risk compensation or informational frictions, making it impossible to cleanly identify either. The risk-neutral benchmark strips out risk pricing so that credit rationing — when it emerges — is unambiguously caused by the information problem.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Parameter Values
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Symbol</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Good-type success probability</td>
<td><span class="math inline">\(p_G\)</span></td>
<td>0.8</td>
</tr>
<tr class="even">
<td>Bad-type success probability</td>
<td><span class="math inline">\(p_B\)</span></td>
<td>0.4</td>
</tr>
<tr class="odd">
<td>Good-type success payoff</td>
<td><span class="math inline">\(y_G\)</span></td>
<td>1.65</td>
</tr>
<tr class="even">
<td>Bad-type success payoff</td>
<td><span class="math inline">\(y_B\)</span></td>
<td>3.30</td>
</tr>
<tr class="odd">
<td>Common expected return</td>
<td><span class="math inline">\(\mu = p_G y_G = p_B y_B\)</span></td>
<td>1.32</td>
</tr>
<tr class="even">
<td>Risk-free gross return</td>
<td><span class="math inline">\(r\)</span></td>
<td>1.05</td>
</tr>
<tr class="odd">
<td>Fraction of type <span class="math inline">\(G\)</span></td>
<td><span class="math inline">\(\alpha\)</span></td>
<td>0.5</td>
</tr>
</tbody>
</table>
<p>These parameters match Diamond (1996): <span class="math inline">\(\mu = PH + (1-P)L = 0.8(1.4) + 0.2(1) = 1.32\)</span> and <span class="math inline">\(p_G = P = 0.8\)</span>. This creates a clean bridge between the two sections. Break-even face values: <span class="math inline">\(f_G^* = 1.05/0.8 = \mathbf{1.3125}\)</span> and <span class="math inline">\(f_B^* = 1.05/0.4 = 2.625\)</span>. Note that <span class="math inline">\(f_G^* = 1.3125\)</span> is exactly Diamond’s unmonitored face value <span class="math inline">\(f^*\)</span> from the ex post section — the same formula, the same number.</p>
</div>
</div>
</section>
<section id="adverse-selection-and-market-exclusion-stiglitz-and-weiss-1981" class="level4" data-number="5.2.1.2">
<h4 data-number="5.2.1.2" class="anchored" data-anchor-id="adverse-selection-and-market-exclusion-stiglitz-and-weiss-1981"><span class="header-section-number">5.2.1.2</span> Adverse Selection and Market Exclusion: Stiglitz and Weiss (1981)</h4>
<p>A borrower participates only if <span class="math inline">\(f \leq y_\theta\)</span>. Since <span class="math inline">\(y_G &lt; y_B\)</span>, good borrowers exit at a lower face value than bad borrowers. This creates a fundamental dilemma: at any <span class="math inline">\(f \leq y_G\)</span> (the pooling zone), the lender’s expected return stays below <span class="math inline">\(r\)</span> — the mix of types is too risky to break even. But raising <span class="math inline">\(f\)</span> above <span class="math inline">\(y_G\)</span> drives good borrowers out entirely, causing a discrete drop in pool quality. The lender can only break even by charging <span class="math inline">\(f_B^* = r/p_B\)</span> and lending exclusively to bad borrowers.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Proposition (Stiglitz-Weiss 1981): Market Exclusion Under Adverse Selection
</div>
</div>
<div class="callout-body-container callout-body">
<p>Good borrowers are excluded from credit markets entirely, even though their projects are socially productive (<span class="math inline">\(\mu &gt; r\)</span>). A pooling equilibrium that satisfies both lender break-even and good-borrower participation is infeasible: the face value required to break even on a pooled loan (<span class="math inline">\(f^{pool}\)</span>) exceeds good borrowers’ participation constraint (<span class="math inline">\(f^{pool} &gt; y_G\)</span>).</p>
</div>
</div>
<div style="margin: 24px 0;">
  <svg width="580" height="330" viewbox="0 0 580 330" style="margin: 0 auto; display: block; font-family: serif;">
    <defs>
      <marker id="arrowSW" markerwidth="10" markerheight="10" refx="9" refy="3" orient="auto">
        <path d="M0,0 L0,6 L9,3 z" fill="#333"></path>
      </marker>
    </defs>
    <!-- Axes -->
    <line x1="80" y1="270" x2="530" y2="270" stroke="#333" stroke-width="1.5" marker-end="url(#arrowSW)"></line>
    <line x1="80" y1="275" x2="80" y2="30" stroke="#333" stroke-width="1.5" marker-end="url(#arrowSW)"></line>
    <text x="540" y="275" font-size="12" fill="#333" font-style="italic">f</text>
    <text x="30" y="28" font-size="11" fill="#333">Π(f)</text>
    <!-- Scale: x = 80 + (f - 1.0)*150; y = 270 - Π*180 -->
    <!-- f=1.0: x=80; f=1.65: x=177.5; f=1.75: x=192.5; f=2.625: x=323.75; f=3.30: x=395 -->
    <!-- Π=0: y=270; Π=0.63: y=157; Π=0.99: y=91.8; Π=0.66: y=151.2; Π=1.05: y=81; Π=1.32: y=32 -->
    <!-- Segment 1: f from 1.0 to 1.65, slope pbar=0.60 -->
    <!-- At f=1.0: Π=0.60; x=80, y=270-108=162 -->
    <!-- At f=1.65: Π=0.99; x=177, y=270-178=92 -->
    <line x1="80" y1="162" x2="177" y2="92" stroke="#1565c0" stroke-width="2.5"></line>
    <!-- Drop at y_G=1.65 -->
    <line x1="177" y1="92" x2="177" y2="151" stroke="#1565c0" stroke-width="2" stroke-dasharray="5,3"></line>
    <!-- Segment 2: f from 1.65 to 3.30, slope p_B=0.40 -->
    <!-- At f=1.65: Π=0.66; x=177, y=270-119=151 -->
    <!-- At f=3.30: Π=1.32; x=80+2.3*150=425, y=270-238=32 -->
    <line x1="177" y1="151" x2="425" y2="32" stroke="#1565c0" stroke-width="2.5"></line>
    <!-- Drop at y_B=3.30 -->
    <line x1="425" y1="32" x2="425" y2="270" stroke="#1565c0" stroke-width="2" stroke-dasharray="5,3"></line>
    <!-- Break-even horizontal line r=1.05, Π=1.05: y=270-189=81 -->
    <line x1="80" y1="81" x2="530" y2="81" stroke="#2e7d32" stroke-width="1.5" stroke-dasharray="7,4"></line>
    <text x="430" y="75" font-size="10" fill="#2e7d32" font-weight="bold">r = 1.05 (break-even)</text>
    <!-- f_B* = 2.625 marker: x = 80 + 1.625*150 = 323.75 ≈ 324 -->
    <circle cx="324" cy="81" r="5" fill="#2e7d32"></circle>
    <line x1="324" y1="81" x2="324" y2="270" stroke="#2e7d32" stroke-width="1.2" stroke-dasharray="4,3"></line>
    <text x="324" y="287" font-size="10" fill="#2e7d32" text-anchor="middle">f*_B = 2.625</text>
    <text x="324" y="299" font-size="9" fill="#2e7d32" text-anchor="middle">(lender breaks even)</text>
    <!-- y_G = 1.65 marker -->
    <line x1="177" y1="270" x2="177" y2="275" stroke="#e53935" stroke-width="1.5"></line>
    <text x="177" y="287" font-size="10" fill="#e53935" text-anchor="middle">y_G = 1.65</text>
    <text x="177" y="299" font-size="9" fill="#e53935" text-anchor="middle">(good types exit)</text>
    <!-- f_G* marker: x = 80 + 0.3125*150 = 126.875 ≈ 127 -->
    <line x1="127" y1="270" x2="127" y2="275" stroke="#e65100" stroke-width="1.5"></line>
    <text x="127" y="287" font-size="10" fill="#e65100" text-anchor="middle">f*_G = 1.3125</text>
    <text x="127" y="299" font-size="9" fill="#e65100" text-anchor="middle">(good type break-even)</text>
    <!-- y_B marker -->
    <line x1="425" y1="270" x2="425" y2="275" stroke="#333" stroke-width="1.5"></line>
    <text x="425" y="285" font-size="10" fill="#333" text-anchor="middle">y_B = 3.30</text>
    <!-- Π level lines -->
    <line x1="75" y1="92" x2="80" y2="92" stroke="#555" stroke-width="1"></line>
    <text x="73" y="96" font-size="9" fill="#555" text-anchor="end">0.99</text>
    <line x1="75" y1="151" x2="80" y2="151" stroke="#555" stroke-width="1"></line>
    <text x="73" y="155" font-size="9" fill="#555" text-anchor="end">0.66</text>
    <!-- Shaded region: f in [1.0, 1.65] — pooling zone, below break-even -->
    <rect x="80" y="81" width="97" height="189" fill="#ffebee" fill-opacity="0.5"></rect>
    <text x="129" y="185" font-size="9" fill="#c62828" text-anchor="middle">Pooling zone:</text>
    <text x="129" y="197" font-size="9" fill="#c62828" text-anchor="middle">Π &lt; r always</text>
    <!-- Slope annotations -->
    <text x="95" y="118" font-size="10" fill="#1565c0">slope = p̄ = 0.60</text>
    <text x="230" y="115" font-size="10" fill="#1565c0">slope = p_B = 0.40</text>
    <!-- Title -->
    <text x="300" y="18" font-size="12" font-weight="bold" text-anchor="middle">Lender Expected Return Π(f): Adverse Selection Excludes Good Borrowers</text>
  </svg>
</div>
<p><strong>Figure</strong>: Lender’s expected return <span class="math inline">\(\Pi(f)\)</span> as a function of face value. For <span class="math inline">\(f \leq y_G = 1.65\)</span> (shaded), both types borrow but <span class="math inline">\(\Pi &lt; r = 1.05\)</span> everywhere — pooling is never profitable. At <span class="math inline">\(f = y_G\)</span>, good types exit (discrete drop). For <span class="math inline">\(f &gt; y_G\)</span>, only bad types borrow; the lender can break even at <span class="math inline">\(f_B^* = 2.625\)</span> (green dot). Good borrowers who would accept face value as low as <span class="math inline">\(f_G^* = 1.3125\)</span> are entirely excluded from the market.</p>
</section>
<section id="the-demand-for-screening" class="level4" data-number="5.2.1.3">
<h4 data-number="5.2.1.3" class="anchored" data-anchor-id="the-demand-for-screening"><span class="header-section-number">5.2.1.3</span> The Demand for Screening</h4>
<p>This creates the demand for a technology that identifies <span class="math inline">\(\theta\)</span> <em>before</em> lending — making <span class="math inline">\(f_G^* = r/p_G\)</span> the sustainable rate for good borrowers.</p>
<hr>
</section>
</section>
<section id="signaling-leland-and-pyle-1977" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="signaling-leland-and-pyle-1977"><span class="header-section-number">5.2.2</span> Signaling: Leland and Pyle (1977)</h3>
<p><strong>Leland and Pyle (1977)</strong> show that <strong>equity retention</strong> solves the adverse selection problem through signaling. Retaining a larger share of one’s own project is costly — the entrepreneur bears undiversified idiosyncratic risk. This cost is lower for high-quality borrowers (higher expected returns offset the risk), so low-quality borrowers cannot profitably mimic. The <strong>single-crossing property</strong> ensures a separating equilibrium: equilibrium retention <span class="math inline">\(e^*(\theta)\)</span> is strictly increasing in <span class="math inline">\(\theta\)</span>, and lenders price loans at <span class="math inline">\(f_\theta^* = r/p_\theta\)</span> upon observing <span class="math inline">\(e^*\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Single-Crossing Property
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Intuition:</strong> High-quality projects generate higher expected returns, so the entrepreneur captures more value from retention. The cost of undiversified risk (bearing <span class="math inline">\(e\)</span>) is relatively lower for the high type, making the swap “more retention for a lower rate” attractive precisely when quality is high.</p>
</div>
</div>
<hr>
</section>
<section id="banks-as-information-producers-ramakrishnan-and-thakor-1984" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="banks-as-information-producers-ramakrishnan-and-thakor-1984"><span class="header-section-number">5.2.3</span> Banks as Information Producers: Ramakrishnan and Thakor (1984)</h3>
<p>LP’s result applies to individual entrepreneurs — the information originates with the borrower, not the bank. <strong>Ramakrishnan and Thakor (1984)</strong> provide the bank-centric solution that properly earns the “information producer” label: the bank <em>actively produces</em> information by hiring specialists who screen borrowers, then aggregates their independent assessments. Pooling <span class="math inline">\(n\)</span> noisy signals drives average estimation error to zero by the LLN — the coalition’s signal becomes arbitrarily precise as <span class="math inline">\(n\)</span> grows. This directly reduces funding costs: depositors face vanishing uncertainty about portfolio quality and accept rates close to <span class="math inline">\(r\)</span>. Specialization (repeated expertise lowers <span class="math inline">\(K\)</span> per loan) and diversification (pooling raises precision) are complements.</p>
<p>The progression across these three models is deliberate: Stiglitz-Weiss establishes the problem (adverse selection excludes good borrowers), LP offers a partial solution (borrowers signal their own type), and RT provides the bank-centric resolution (banks actively screen and aggregate information). Fama (1985) then asks what this information production looks like from the outside — and finds that the market treats the bank’s willingness to lend as a quality signal in its own right.</p>
<hr>
</section>
<section id="banks-as-certifiers-fama-1985" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="banks-as-certifiers-fama-1985"><span class="header-section-number">5.2.4</span> Banks as Certifiers: Fama (1985)</h3>
<section id="what-makes-bank-loans-special" class="level4" data-number="5.2.4.1">
<h4 data-number="5.2.4.1" class="anchored" data-anchor-id="what-makes-bank-loans-special"><span class="header-section-number">5.2.4.1</span> What Makes Bank Loans Special?</h4>
<p>Fama (1985) poses a puzzle: if banks are simply financial intermediaries, why do firms borrow from banks rather than issuing bonds directly? Bonds reach many investors; bank loans require a bilateral relationship. If the two were equivalent on an information-adjusted basis, firms would prefer the cheaper bond market. Yet many firms — especially smaller ones — rely exclusively on bank credit.</p>
<p>Fama’s answer: <strong>banks certify borrower quality</strong> in a way the bond market cannot. The bond market prices securities on public information; banks acquire private information through the ongoing relationship — observing cash flows, repayment history, and deposit account activity. The bank’s willingness to lend is itself informative: letting <span class="math inline">\(s_i = 1\)</span> if firm <span class="math inline">\(i\)</span> has a credit line,</p>
<p><span class="math display">\[\Pr(\theta = G \mid s_i = 1) &gt; \Pr(\theta = G \mid s_i = 0) = \alpha\]</span></p>
<p>Investors update upward upon observing the bank’s decision, so firms with credit lines can issue bonds at lower spreads.</p>
<p><strong>Evidence</strong>:</p>
<ol type="1">
<li>Firms pay higher rates on bank loans than on comparable bonds — the premium reflects the cost of private monitoring</li>
<li>Firms maintain credit lines even at positive commitment fees, suggesting the relationship provides something the bond market cannot</li>
<li>Bank credit line renewals raise borrowing firms’ stock prices; bond issues do not — the market treats the bank’s willingness to lend as a quality signal</li>
</ol>
<hr>
<hr>
</section>
</section>
</section>
<section id="ex-post-banks-as-delegated-monitors" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="ex-post-banks-as-delegated-monitors"><span class="header-section-number">5.3</span> Ex Post: Banks as Delegated Monitors</h2>
<p>The previous section addressed the <em>ex ante</em> information problem: how do lenders identify good borrowers <em>before</em> lending? This section addresses the <em>ex post</em> information problem: given that lending has occurred, how does the lender verify the borrower’s realized return and enforce repayment? We follow Diamond (1984, 1996) throughout.</p>
<p>Direct finance does not solve this problem — it merely relocates it. Any individual investor who could monitor a borrower lacks the capital to fund the project alone, while the many small investors who together have sufficient capital cannot monitor without ruinous duplication or free-riding. Banks solve this <strong>organizational problem</strong> — monitoring is socially valuable (<span class="math inline">\(S &gt; K\)</span>, where <span class="math inline">\(S\)</span> is the liquidation surplus recovered and <span class="math inline">\(K\)</span> is the per-investor monitoring cost) but prohibitive when duplicated (<span class="math inline">\(mK \gg S\)</span>, where <span class="math inline">\(m\)</span> is the number of investors) — by consolidating monitoring into a single agent and using diversification to eliminate the cost of delegation. The organizational form of the bank (monitored loans on the asset side, fixed-rate deposits on the liability side) follows directly from this.</p>
<section id="the-environment" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="the-environment"><span class="header-section-number">5.3.1</span> The Environment</h3>
<section id="setup-1" class="level4" data-number="5.3.1.1">
<h4 data-number="5.3.1.1" class="anchored" data-anchor-id="setup-1"><span class="header-section-number">5.3.1.1</span> Setup</h4>
<p>The model (Diamond 1996) has the following structure:</p>
<ul>
<li>A <strong>borrower</strong> needs to raise <strong>1</strong> ($1 million) of external capital at <span class="math inline">\(t = 0\)</span></li>
<li>There are <strong><span class="math inline">\(m = 10{,}000\)</span> investors</strong>, each with $100 <span class="math inline">\(= 0.0001\)</span> to invest; each investor’s capital is too small to fund the project alone</li>
<li>All parties are <strong>risk-neutral</strong> and require a gross expected return of <span class="math inline">\(r = 1.05\)</span> (5%)</li>
<li>The borrower’s project returns a gross value <span class="math inline">\(V\)</span> at <span class="math inline">\(t = 1\)</span>:</li>
</ul>
<p><span class="math display">\[
V = \begin{cases} H = 1.4 &amp; \text{with probability } P = 0.8 \\ L = 1 &amp; \text{with probability } 1 - P = 0.2 \end{cases}
\]</span></p>
<ul>
<li>The distribution of <span class="math inline">\(V\)</span> is <strong>common knowledge</strong>, but <strong>only the borrower observes the realized value</strong> — unless an investor pays a monitoring cost</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Parameter Values
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Symbol</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Project return (high)</td>
<td><span class="math inline">\(H\)</span></td>
<td>1.4</td>
</tr>
<tr class="even">
<td>Project return (low)</td>
<td><span class="math inline">\(L\)</span></td>
<td>1</td>
</tr>
<tr class="odd">
<td>Probability of high return</td>
<td><span class="math inline">\(P\)</span></td>
<td>0.8</td>
</tr>
<tr class="even">
<td>Expected project return</td>
<td><span class="math inline">\(\mathbb{E}[V] = PH + (1-P)L\)</span></td>
<td>1.32</td>
</tr>
<tr class="odd">
<td>Required gross return</td>
<td><span class="math inline">\(r\)</span></td>
<td>1.05</td>
</tr>
<tr class="even">
<td>Number of investors per project</td>
<td><span class="math inline">\(m\)</span></td>
<td>10,000</td>
</tr>
<tr class="odd">
<td>Monitoring cost per investor</td>
<td><span class="math inline">\(K\)</span></td>
<td>0.0002</td>
</tr>
</tbody>
</table>
<p>The project is feasible: <span class="math inline">\(\mathbb{E}[V] = 1.32 &gt; r = 1.05\)</span>. The social surplus per project is <span class="math inline">\(1.32 - 1.05 = 0.27\)</span>.</p>
</div>
</div>
</section>
<section id="the-information-problem" class="level4" data-number="5.3.1.2">
<h4 data-number="5.3.1.2" class="anchored" data-anchor-id="the-information-problem"><span class="header-section-number">5.3.1.2</span> The Information Problem</h4>
<p>The borrower observes the realized <span class="math inline">\(V\)</span> first. This creates a <strong>moral hazard</strong> problem: the borrower can claim <span class="math inline">\(V\)</span> was as small as possible, retaining the difference. The lender must design a contract that either:</p>
<ol type="1">
<li>Gives the borrower an <strong>incentive to repay</strong> without verification, or</li>
<li>Allows the lender to <strong>verify the true return</strong> by paying a monitoring cost <span class="math inline">\(K\)</span></li>
</ol>
<p><strong>Monitoring cost</strong>: <span class="math inline">\(K = 0.0002\)</span> ($200) per investor per borrower. Monitoring allows an investor to directly observe the firm’s operations and cash flows.</p>
<p><strong>Liquidation</strong>: When monitoring is infeasible, the lender’s only enforcement tool is <strong>liquidation</strong> of the borrower’s assets. Diamond (1996) assumes liquidation yields <strong>zero</strong> to both lender and borrower — it is purely destructive. This focuses attention on the social cost of failing to monitor.</p>
</section>
<section id="why-equity-fails" class="level4" data-number="5.3.1.3">
<h4 data-number="5.3.1.3" class="anchored" data-anchor-id="why-equity-fails"><span class="header-section-number">5.3.1.3</span> Why Equity Fails</h4>
<p>A natural first candidate is an <strong>equity contract</strong>: the investor receives a fraction <span class="math inline">\(a\)</span> of the borrower’s reported return <span class="math inline">\(\hat{V}\)</span>. Because the borrower observes the true <span class="math inline">\(V\)</span> first and the investor cannot verify it, the borrower always reports <span class="math inline">\(\hat{V} = L\)</span> (the minimum), retaining <span class="math inline">\(H - L\)</span> when <span class="math inline">\(V = H\)</span>. Investors recover nothing regardless of the true outcome. Any contract based on reported returns fails — forcing truthful reporting requires either monitoring or a fixed promised payment (debt) that the borrower has an incentive to meet without monitoring.</p>
</section>
</section>
<section id="the-costly-state-verification-framework" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="the-costly-state-verification-framework"><span class="header-section-number">5.3.2</span> The Costly State Verification Framework</h3>
<section id="the-general-problem-townsend-1979" class="level4" data-number="5.3.2.1">
<h4 data-number="5.3.2.1" class="anchored" data-anchor-id="the-general-problem-townsend-1979"><span class="header-section-number">5.3.2.1</span> The General Problem (Townsend 1979)</h4>
<p>The brief discussion above shows why equity fails. To derive the optimal contract rigorously, we use the <strong>Costly State Verification (CSV)</strong> framework of Townsend (1979). The CSV framework asks: given that the lender can verify the borrower’s return by paying cost <span class="math inline">\(K\)</span>, what contract maximizes total surplus while satisfying both parties’ participation constraints?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Costly State Verification
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the <strong>CSV problem</strong> (Townsend 1979), a borrower observes the realized project return <span class="math inline">\(V\)</span> but the lender does not. The lender may pay a fixed cost <span class="math inline">\(K\)</span> to <strong>verify</strong> the true return. A contract specifies:</p>
<ol type="1">
<li>In which states to monitor (where to pay <span class="math inline">\(K\)</span> and observe <span class="math inline">\(V\)</span> directly)</li>
<li>What payment to require conditional on (i) the borrower’s voluntary report without monitoring, or (ii) the verified return after monitoring</li>
</ol>
<p>The contracting problem is to design this mapping to minimize total monitoring costs subject to incentive compatibility and the lender’s break-even constraint.</p>
</div>
</div>
<p>Townsend’s key insight is that the optimal monitoring rule is <strong>deterministic</strong>: the lender commits in advance to monitor in certain states and not others. Randomized monitoring (paying <span class="math inline">\(K\)</span> with some probability in each state) is dominated — it introduces risk without saving costs.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why Deterministic Monitoring Dominates Randomized Monitoring
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose the lender monitors with probability <span class="math inline">\(\pi &lt; 1\)</span> in some state. For this to deter misreporting, the expected penalty when caught must cover the gain from lying:</p>
<p><span class="math display">\[\pi \times \text{penalty} \geq \text{gain from misreporting}\]</span></p>
<p>Since <span class="math inline">\(\pi &lt; 1\)</span>, the required penalty is <em>larger</em> than under deterministic monitoring. But large penalties are either infeasible (limited borrower wealth) or wasteful. Meanwhile the lender still pays expected monitoring cost <span class="math inline">\(\pi K\)</span> — not zero.</p>
<p>Switch to deterministic monitoring in those same states. The lender monitors with certainty, observes the true return, and collects it directly. No artificial penalty is needed — certain detection is itself sufficient deterrence. Three advantages follow:</p>
<ol type="1">
<li><strong>No penalty required</strong>: truth is extracted directly upon monitoring</li>
<li><strong>No added risk</strong>: randomization imposes noise on risk-neutral parties with no compensating benefit</li>
<li><strong>Stronger incentive compatibility</strong>: certain detection leaves the borrower no incentive to gamble on misreporting</li>
</ol>
<p><strong>Formal result (Townsend 1979)</strong>: with risk-neutral parties, for any randomized contract satisfying incentive compatibility, there exists a deterministic contract achieving the same expected payments at weakly lower monitoring cost. Randomization never strictly helps.</p>
</div>
</div>
<p>This immediately raises the question: <em>which</em> states? The answer follows from incentive compatibility. The lender only needs to monitor in states where the borrower <em>would</em> misreport if unmonitored — that is, states where the borrower cannot make the required payment voluntarily. In states where the borrower can and does pay voluntarily, monitoring is pure waste.</p>
</section>
<section id="optimal-contract-standard-debt-gale-and-hellwig-1985" class="level4" data-number="5.3.2.2">
<h4 data-number="5.3.2.2" class="anchored" data-anchor-id="optimal-contract-standard-debt-gale-and-hellwig-1985"><span class="header-section-number">5.3.2.2</span> Optimal Contract: Standard Debt (Gale and Hellwig 1985)</h4>
<p>Gale and Hellwig (1985) showed that the <strong>standard debt contract</strong> is the unique contract that implements this optimal monitoring rule. Set a fixed face value <span class="math inline">\(f\)</span>: the borrower pays <span class="math inline">\(f\)</span> in good states (voluntarily, no monitoring needed) and triggers monitoring only in bad states (when unable to pay). Any contract requiring monitoring in good states wastes <span class="math inline">\(K\)</span> unnecessarily; any contract without monitoring in bad states invites misreporting. Debt is the only contract that monitors exactly when needed.</p>
<p>A <strong>standard debt contract</strong> with face value <span class="math inline">\(f\)</span> works as follows:</p>
<ul>
<li><strong>Good state</strong> (<span class="math inline">\(V = H \geq f\)</span>): The borrower pays <span class="math inline">\(f\)</span> voluntarily and keeps <span class="math inline">\(H - f &gt; 0\)</span>. No monitoring is needed — the borrower prefers paying <span class="math inline">\(f\)</span> over triggering monitoring and full extraction of <span class="math inline">\(H\)</span>.</li>
<li><strong>Bad state</strong> (<span class="math inline">\(V = L &lt; f\)</span>): The borrower cannot pay <span class="math inline">\(f\)</span>. The lender <strong>monitors</strong> (cost <span class="math inline">\(K\)</span>), verifies <span class="math inline">\(V = L\)</span>, and collects <span class="math inline">\(L\)</span>.</li>
</ul>
<p>Expected monitoring cost <span class="math inline">\(= (1-P) \times K\)</span> — monitoring occurs only in default states, not good states.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Proposition (Gale-Hellwig 1985): Standard Debt Minimizes Monitoring Costs
</div>
</div>
<div class="callout-body-container callout-body">
<p>Among all incentive-compatible contracts, the standard debt contract minimizes expected monitoring costs. The lender monitors <strong>only in default states</strong>. The face value <span class="math inline">\(f\)</span> satisfies the lender’s break-even constraint:</p>
<p><span class="math display">\[
P \cdot f + (1 - P)(L - K) = r
\]</span></p>
<p>With our parameters (<span class="math inline">\(P = 0.8\)</span>, <span class="math inline">\(L = 1\)</span>, <span class="math inline">\(K = 0.0002\)</span>, <span class="math inline">\(r = 1.05\)</span>):</p>
<p><span class="math display">\[0.8f + 0.2(1 - 0.0002) = 1.05 \quad \Rightarrow \quad f \approx 1.0625\]</span></p>
<p>The <strong>monitored loan rate is approximately 6.25%</strong>. Expected monitoring cost per loan <span class="math inline">\(= (1-P)K = 0.2 \times 0.0002 = 0.00004\)</span> — nearly zero.</p>
</div>
</div>
<p><strong>Why is debt optimal?</strong> Any contract with variable payments in the good state — such as equity — requires verification in the good state too, since the borrower would underreport good outcomes. Debt concentrates the lender’s monitoring effort on the states where it is actually needed. A well-designed debt contract minimizes total monitoring cost <span class="math inline">\((1-P)K\)</span> by eliminating all monitoring in good states.</p>
</section>
<section id="diamond-1996-a-simplified-special-case" class="level4" data-number="5.3.2.3">
<h4 data-number="5.3.2.3" class="anchored" data-anchor-id="diamond-1996-a-simplified-special-case"><span class="header-section-number">5.3.2.3</span> Diamond (1996): A Simplified Special Case</h4>
<p>Diamond (1996) asks a sharper question: given that monitoring is available at cost <span class="math inline">\(K\)</span>, how should monitoring be <em>organized</em> when many small investors must pool capital? To focus attention on the delegation problem, Diamond simplifies the CSV framework in one important way:</p>
<blockquote class="blockquote">
<p><strong>Instead of the lender verifying a bad-state return <span class="math inline">\(L &gt; 0\)</span> by paying <span class="math inline">\(K\)</span>, the only enforcement tool without monitoring is liquidation — which yields zero to both parties.</strong></p>
</blockquote>
<p>In Diamond’s setup:</p>
<ul>
<li><strong>Without monitoring</strong> (no lending relationship): If the borrower defaults, the lender <strong>liquidates</strong> the borrower’s assets. Liquidation is <strong>completely destructive</strong> — both parties receive 0. The bad-state value <span class="math inline">\(L = 1\)</span> is entirely destroyed.</li>
<li><strong>With monitoring</strong> (lending relationship established): The lender can observe <span class="math inline">\(V = L = 1\)</span> and <strong>accept <span class="math inline">\(L = 1\)</span> rather than liquidating</strong>. “Monitoring” in Diamond means the ability to verify the bad-state outcome and avoid wasteful liquidation.</li>
</ul>
<p>The monitoring cost <span class="math inline">\(K = 0.0002\)</span> is the cost of establishing and maintaining this observational relationship. Liquidation itself is costless to execute, but destroys real value.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How Diamond (1996) Maps to the General CSV Framework
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>General CSV (Townsend 1979 / Gale-Hellwig 1985)</th>
<th>Diamond (1996) Simplification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bad state, no monitoring</strong></td>
<td>Borrower misreports; lender gets self-reported <span class="math inline">\(L\)</span></td>
<td>Lender <strong>liquidates</strong>; both get <strong>0</strong></td>
</tr>
<tr class="even">
<td><strong>Bad state, with monitoring</strong></td>
<td>Lender pays <span class="math inline">\(K\)</span>, verifies <span class="math inline">\(V = L\)</span>, collects <span class="math inline">\(L - K\)</span> net</td>
<td>Lender pays <span class="math inline">\(K\)</span>, observes <span class="math inline">\(V = L\)</span>, accepts <span class="math inline">\(L = 1\)</span></td>
</tr>
<tr class="odd">
<td><strong>Social waste from not monitoring</strong></td>
<td>Incentive distortion from misreporting</td>
<td><span class="math inline">\(L = 1\)</span> destroyed per bad-state occurrence</td>
</tr>
<tr class="even">
<td><strong>Expected social cost (unmonitored)</strong></td>
<td>Misreporting equilibrium collapses equity</td>
<td><span class="math inline">\(S = (1-P) \cdot L = 0.2\)</span> per borrower</td>
</tr>
<tr class="odd">
<td><strong>Monitored face value</strong></td>
<td><span class="math inline">\(f \approx 1.0625\)</span></td>
<td><span class="math inline">\(f \approx 1.0625\)</span> (identical formula)</td>
</tr>
<tr class="even">
<td><strong>Unmonitored face value</strong></td>
<td>Equity collapses; no meaningful benchmark</td>
<td><span class="math inline">\(f^* = 1.3125\)</span> (liquidation-enforced debt)</td>
</tr>
</tbody>
</table>
<p>Diamond’s liquidation assumption creates a <strong>concrete, measurable social cost</strong> (<span class="math inline">\(S = 0.2\)</span>) from not monitoring. It also generates a well-defined unmonitored contract: debt enforced by the liquidation threat alone, with no verification required.</p>
</div>
</div>
<p>Diamond’s liquidation assumption makes the <strong>unmonitored debt contract</strong> self-enforcing without verification: “Pay me at least <span class="math inline">\(f\)</span>, or I liquidate and we both get 0.” The borrower complies in state <span class="math inline">\(H\)</span> and defaults in state <span class="math inline">\(L\)</span>, pinning down <span class="math inline">\(f^* = 1.3125\)</span>. The central question: when is monitoring organizationally feasible?</p>
</section>
</section>
<section id="unmonitored-debt" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="unmonitored-debt"><span class="header-section-number">5.3.3</span> Unmonitored Debt</h3>
<section id="why-debt-works" class="level4" data-number="5.3.3.1">
<h4 data-number="5.3.3.1" class="anchored" data-anchor-id="why-debt-works"><span class="header-section-number">5.3.3.1</span> Why Debt Works</h4>
<p>We now work through Diamond (1996)’s numerical implementation. Suppose monitoring is <strong>unavailable</strong> — the lender has no established relationship with the borrower and cannot verify the realized return. The only enforcement tool is liquidation. Consider a debt contract with face value <span class="math inline">\(f\)</span>:</p>
<ul>
<li>If the borrower pays at least <span class="math inline">\(f\)</span>: no liquidation; borrower keeps <span class="math inline">\(V - f\)</span></li>
<li>If the borrower pays less than <span class="math inline">\(f\)</span>: lender liquidates; both get 0</li>
</ul>
<p>The borrower’s choices in each state:</p>
<ul>
<li><strong>State <span class="math inline">\(H\)</span> (<span class="math inline">\(V = 1.4\)</span>):</strong> Pay <span class="math inline">\(f\)</span> and keep <span class="math inline">\(1.4 - f &gt; 0\)</span>, or default and get liquidated (keep 0). The borrower pays <span class="math inline">\(f\)</span> as long as <span class="math inline">\(f \leq 1.4\)</span>.</li>
<li><strong>State <span class="math inline">\(L\)</span> (<span class="math inline">\(V = 1\)</span>):</strong> If <span class="math inline">\(f &gt; 1\)</span>, the borrower cannot pay. Default and liquidation occur. Both get 0.</li>
</ul>
<p>The lender receives <span class="math inline">\(f\)</span> in state <span class="math inline">\(H\)</span> and <span class="math inline">\(0\)</span> in state <span class="math inline">\(L\)</span>. The lender’s break-even condition:</p>
<p><span class="math display">\[P \cdot f + (1 - P) \cdot 0 = r \quad \Rightarrow \quad 0.8 f = 1.05 \quad \Rightarrow \quad \boxed{f^* = 1.3125}\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Connection to Adverse Selection: <span class="math inline">\(f^* = f_G^*\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice that <span class="math inline">\(f^* = 1.3125\)</span> here is identical to the break-even face value for good borrowers in the Stiglitz-Weiss section: <span class="math inline">\(f_G^* = r/p_G = 1.05/0.8 = 1.3125\)</span>. The formula is the same because the underlying logic is the same — in both cases the lender is repaid only in the good state, and <span class="math inline">\(P = p_G = 0.8\)</span>.</p>
<p>The two sections are examining the same debt contract from different angles. Ex ante (Stiglitz-Weiss), the problem is <em>identifying</em> which borrowers have <span class="math inline">\(p = 0.8\)</span>. Ex post (Diamond), the problem is <em>verifying</em> whether the good state actually occurred. Banks solve both problems — but the contract they use is identical.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Unmonitored Debt: Numerical Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>With face value <span class="math inline">\(f^* = 1.3125\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>State</th>
<th>Probability</th>
<th>Borrower pays</th>
<th>Lender receives</th>
<th>Borrower keeps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H = 1.4\)</span></td>
<td>0.8</td>
<td>1.3125</td>
<td>1.3125</td>
<td>0.0875</td>
</tr>
<tr class="even">
<td><span class="math inline">\(L = 1\)</span></td>
<td>0.2</td>
<td>0 (liquidated)</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Lender’s expected return: <span class="math inline">\(0.8 \times 1.3125 = 1.05\)</span> ✓</p>
<p>The borrower voluntarily pays 1.3125 in the good state because it is the lowest payment that avoids liquidation. The threat of liquidation makes the contract self-enforcing — <strong>no monitoring needed</strong>.</p>
</div>
</div>
</section>
<section id="the-deadweight-cost-liquidation-waste" class="level4" data-number="5.3.3.2">
<h4 data-number="5.3.3.2" class="anchored" data-anchor-id="the-deadweight-cost-liquidation-waste"><span class="header-section-number">5.3.3.2</span> The Deadweight Cost: Liquidation Waste</h4>
<p>Unmonitored debt is self-enforcing but <strong>inefficient</strong>. In the bad state (<span class="math inline">\(V = L = 1\)</span>), liquidation yields nothing to either party — yet the project produced a real value of <span class="math inline">\(L = 1\)</span>.</p>
<p>The <strong>liquidation waste</strong> per borrower is:</p>
<p><span class="math display">\[S \equiv (1 - P) \times L = 0.2 \times 1 = 0.2\]</span></p>
<p>This <span class="math inline">\(S = 0.2\)</span> is the expected value destroyed by liquidation — and the most anyone would pay to eliminate it. Since <span class="math inline">\(K = 0.0002 \ll S = 0.2\)</span>, monitoring is enormously valuable for a single lender. The problem arises when capital must be raised from many small investors.</p>
</section>
</section>
<section id="the-value-of-monitoring" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="the-value-of-monitoring"><span class="header-section-number">5.3.4</span> The Value of Monitoring</h3>
<section id="monitored-debt" class="level4" data-number="5.3.4.1">
<h4 data-number="5.3.4.1" class="anchored" data-anchor-id="monitored-debt"><span class="header-section-number">5.3.4.1</span> Monitored Debt</h4>
<p>If a lender can verify the borrower’s return at cost <span class="math inline">\(K\)</span>, she can offer a better contract. This is the <strong>CSV-optimal contract</strong> from the Gale-Hellwig (1985) result: monitor only in the bad state, accept <span class="math inline">\(L\)</span> rather than liquidating, and set the face value to cover monitoring costs. Under <strong>monitored debt</strong> with face value <span class="math inline">\(f\)</span>:</p>
<ul>
<li>If <span class="math inline">\(V = H = 1.4\)</span>: Borrower pays <span class="math inline">\(f\)</span> voluntarily (no monitoring needed)</li>
<li>If <span class="math inline">\(V = L = 1\)</span>: Lender monitors, observes <span class="math inline">\(V = 1\)</span>, and <strong>accepts 1 instead of liquidating</strong></li>
</ul>
<p>The lender receives <span class="math inline">\(f\)</span> in the good state and <span class="math inline">\(1\)</span> in the bad state. Monitoring costs <span class="math inline">\((1-P)K = 0.2 \times 0.0002 = 0.00004\)</span> in expectation per loan (monitoring is only needed in the bad state). The lender’s break-even:</p>
<p><span class="math display">\[P \cdot f + (1-P) \cdot 1 - (1-P) K = r\]</span> <span class="math display">\[0.8f + 0.2 - 0.00004 = 1.05 \quad \Rightarrow \quad f \approx 1.0625\]</span></p>
<p>The monitored loan rate is approximately <strong>6.25%</strong> — versus the unmonitored rate of <strong>31.25%</strong>. The borrower is far better off:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 48%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Unmonitored debt</th>
<th>Monitored debt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Face value</td>
<td>1.3125</td>
<td>≈ 1.0625</td>
</tr>
<tr class="even">
<td>Borrower’s expected surplus</td>
<td><span class="math inline">\(0.8 \times 0.0875 = 0.070\)</span></td>
<td><span class="math inline">\(0.8 \times 0.3375 = 0.270\)</span></td>
</tr>
<tr class="odd">
<td>Lender’s expected return</td>
<td>1.05</td>
<td>1.05</td>
</tr>
<tr class="even">
<td>Liquidation waste</td>
<td><span class="math inline">\(S = 0.2\)</span></td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Monitoring captures the full value <span class="math inline">\(S = 0.2\)</span> that is otherwise wasted. The monitoring cost <span class="math inline">\(\approx 0.00004\)</span> is negligible.</p>
</section>
</section>
<section id="why-direct-monitoring-fails" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="why-direct-monitoring-fails"><span class="header-section-number">5.3.5</span> Why Direct Monitoring Fails</h3>
<section id="the-duplication-problem" class="level4" data-number="5.3.5.1">
<h4 data-number="5.3.5.1" class="anchored" data-anchor-id="the-duplication-problem"><span class="header-section-number">5.3.5.1</span> The Duplication Problem</h4>
<p>Now impose the realistic constraint: the borrower needs to raise 1 from <span class="math inline">\(m = 10{,}000\)</span> small investors, each contributing 0.0001.</p>
<p>If every investor monitors independently:</p>
<p><span class="math display">\[\text{Total monitoring cost} = m \times K = 10{,}000 \times 0.0002 = 2\]</span></p>
<p>This exceeds the entire expected project return of 1.32. The total monitoring cost <span class="math inline">\(mK = 2\)</span> vastly exceeds the savings from monitoring <span class="math inline">\(S = 0.2\)</span>.</p>
<p><strong>Direct monitoring by all investors is prohibitively expensive.</strong></p>
</section>
<section id="free-riding-worsens-the-problem" class="level4" data-number="5.3.5.2">
<h4 data-number="5.3.5.2" class="anchored" data-anchor-id="free-riding-worsens-the-problem"><span class="header-section-number">5.3.5.2</span> Free-Riding Worsens the Problem</h4>
<p>Suppose investors try to designate a single monitor. This creates a <strong>public goods problem</strong>: the information obtained benefits all investors, so each prefers to free-ride. In equilibrium, monitoring collapses. The only viable contract under direct finance is unmonitored widely held debt with <span class="math inline">\(f = 1.3125\)</span>.</p>
<div style="margin: 20px 0;">
  <svg width="580" height="230" viewbox="0 0 580 230" style="margin: 0 auto; display: block; font-family: serif;">
    <text x="290" y="18" font-size="13" font-weight="bold" text-anchor="middle">The Monitoring Dilemma Under Direct Finance</text>
    <!-- Left box: single lender -->
    <rect x="20" y="30" width="235" height="158" rx="6" fill="#e8f5e9" stroke="#2e7d32" stroke-width="1.5"></rect>
    <text x="138" y="52" font-size="12" font-weight="bold" text-anchor="middle" fill="#1b5e20">Single Large Lender</text>
    <text x="138" y="71" font-size="11" text-anchor="middle">Monitoring cost: K = 0.0002</text>
    <text x="138" y="89" font-size="11" text-anchor="middle">Savings: S = 0.2</text>
    <text x="138" y="107" font-size="11" text-anchor="middle">Net gain: S − K = 0.1998 &gt; 0</text>
    <rect x="35" y="122" width="205" height="52" rx="4" fill="#c8e6c9" stroke="#2e7d32" stroke-width="1"></rect>
    <text x="138" y="141" font-size="11" text-anchor="middle" font-weight="bold" fill="#1b5e20">Monitoring is worthwhile</text>
    <text x="138" y="158" font-size="10" text-anchor="middle" fill="#1b5e20">But can't fund $1M alone</text>
    <text x="138" y="171" font-size="10" text-anchor="middle" fill="#1b5e20">(m = 10,000 investors needed)</text>
    <!-- Right box: m lenders -->
    <rect x="325" y="30" width="235" height="158" rx="6" fill="#ffebee" stroke="#c62828" stroke-width="1.5"></rect>
    <text x="443" y="52" font-size="12" font-weight="bold" text-anchor="middle" fill="#b71c1c">m = 10,000 Small Lenders</text>
    <text x="443" y="71" font-size="11" text-anchor="middle">Direct monitoring cost: mK = 2</text>
    <text x="443" y="89" font-size="11" text-anchor="middle">Savings: S = 0.2</text>
    <text x="443" y="107" font-size="11" text-anchor="middle">Net gain: S − mK = −1.8 &lt; 0</text>
    <rect x="340" y="122" width="205" height="52" rx="4" fill="#ffcdd2" stroke="#c62828" stroke-width="1"></rect>
    <text x="443" y="141" font-size="11" text-anchor="middle" font-weight="bold" fill="#b71c1c">Monitoring is not worthwhile</text>
    <text x="443" y="158" font-size="10" text-anchor="middle" fill="#b71c1c">Use unmonitored debt: f = 1.3125</text>
    <text x="443" y="171" font-size="10" text-anchor="middle" fill="#b71c1c">Accept waste S = 0.2 per borrower</text>
    <text x="290" y="210" font-size="10" text-anchor="middle" fill="#555" font-style="italic">Monitoring is socially valuable (S &gt; K) but duplicated costs (mK &gt;&gt; S) make direct monitoring infeasible.</text>
  </svg>
</div>
<p>The challenge: how to have <strong>one entity monitor on behalf of many investors</strong> without duplicating costs?</p>
</section>
</section>
<section id="the-bank-as-delegated-monitor" class="level3" data-number="5.3.6">
<h3 data-number="5.3.6" class="anchored" data-anchor-id="the-bank-as-delegated-monitor"><span class="header-section-number">5.3.6</span> The Bank as Delegated Monitor</h3>
<section id="structure-of-the-bank" class="level4" data-number="5.3.6.1">
<h4 data-number="5.3.6.1" class="anchored" data-anchor-id="structure-of-the-bank"><span class="header-section-number">5.3.6.1</span> Structure of the Bank</h4>
<p>The bank intermediates between depositors and borrowers:</p>
<ol type="1">
<li><strong>Depositors</strong> deposit savings with the bank. Each depositor gets a deposit contract with promised total payment <span class="math inline">\(B\)</span>.</li>
<li><strong>The bank</strong> lends to borrowers, monitors them, and collects repayments.</li>
<li><strong>Borrowers</strong> deal only with the bank — not 10,000 individual investors.</li>
</ol>
<p>This concentrates monitoring in a single entity. The bank, like a single large investor, captures the full value <span class="math inline">\(S\)</span> at cost <span class="math inline">\(K\)</span> per borrower. But there is an immediate new problem.</p>
</section>
<section id="the-delegation-problem" class="level4" data-number="5.3.6.2">
<h4 data-number="5.3.6.2" class="anchored" data-anchor-id="the-delegation-problem"><span class="header-section-number">5.3.6.2</span> The Delegation Problem</h4>
<p>Small depositors face the same moral hazard with the bank that investors faced with borrowers: the bank observes loan repayments but depositors do not. The bank solves the first problem (borrower misreporting) by monitoring — but creates an analogous second problem. Diamond’s key insight: <strong>diversification solves the second problem without requiring depositors to monitor the bank.</strong></p>
</section>
<section id="solution-liquidation-threat-diversification" class="level4" data-number="5.3.6.3">
<h4 data-number="5.3.6.3" class="anchored" data-anchor-id="solution-liquidation-threat-diversification"><span class="header-section-number">5.3.6.3</span> Solution: Liquidation Threat + Diversification</h4>
<p>The bank issues <strong>fixed-rate, unmonitored deposits</strong> to small investors — the same liquidation-enforcement logic applies:</p>
<ul>
<li>If the bank pays at least the promised amount: no liquidation, bank keeps the residual</li>
<li>If the bank pays less: depositors liquidate the bank (yields zero to everyone)</li>
</ul>
<p>The key question is: <strong>how often does the bank fail to pay?</strong> With a single loan, the bank fails whenever the borrower defaults — frequently. With many independent loans, the bank’s income is nearly deterministic and bank failure becomes rare. This is the role of diversification.</p>
</section>
</section>
<section id="the-one-loan-bank" class="level3" data-number="5.3.7">
<h3 data-number="5.3.7" class="anchored" data-anchor-id="the-one-loan-bank"><span class="header-section-number">5.3.7</span> The One-Loan Bank</h3>
<p>Suppose the bank monitors <strong>one borrower</strong> on behalf of 10,000 depositors. The bank collects <span class="math inline">\(f\)</span> (success) or <span class="math inline">\(1\)</span> (monitored failure) from the borrower. For depositors to earn 5%:</p>
<p><span class="math display">\[P \times B = r \quad \Rightarrow \quad 0.8B = 1.05 \quad \Rightarrow \quad B = 1.3125\]</span></p>
<p>But the bank needs to pay <span class="math inline">\(B = 1.3125\)</span> when it only collects <span class="math inline">\(1\)</span> from a defaulting borrower. Since <span class="math inline">\(1 &lt; 1.3125\)</span>, the bank is liquidated whenever the borrower defaults — <strong>with probability <span class="math inline">\(1 - P = 0.2\)</span></strong>.</p>
<p>The one-loan bank reduces monitoring duplication but achieves <strong>zero reduction in financial distress</strong>. The bank fails just as often as if there were no intermediary. Depositors still face a bank that fails 20% of the time. Without diversification, delegation provides no efficiency gain.</p>
</section>
<section id="the-two-loan-bank" class="level3" data-number="5.3.8">
<h3 data-number="5.3.8" class="anchored" data-anchor-id="the-two-loan-bank"><span class="header-section-number">5.3.8</span> The Two-Loan Bank</h3>
<section id="setup-2" class="level4" data-number="5.3.8.1">
<h4 data-number="5.3.8.1" class="anchored" data-anchor-id="setup-2"><span class="header-section-number">5.3.8.1</span> Setup</h4>
<p>The banker monitors <strong>two borrowers</strong> (<span class="math inline">\(n = 2\)</span>), raising deposits from 20,000 investors. Returns <span class="math inline">\(V_1, V_2\)</span> are i.i.d. The banker gives each borrower a monitored debt contract with face value <span class="math inline">\(f\)</span>:</p>
<ul>
<li>If <span class="math inline">\(V_i = H = 1.4\)</span>: Borrower <span class="math inline">\(i\)</span> pays <span class="math inline">\(f\)</span> to the bank</li>
<li>If <span class="math inline">\(V_i = L = 1\)</span>: Bank monitors borrower <span class="math inline">\(i\)</span>, accepts 1</li>
</ul>
<p>The bank’s total income distribution:</p>
<table class="table-striped caption-top table">
<caption>Distribution of two-loan bank’s total income</caption>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Probability</th>
<th>Bank income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Both succeed</td>
<td><span class="math inline">\(P^2 = 0.64\)</span></td>
<td><span class="math inline">\(2f\)</span></td>
</tr>
<tr class="even">
<td>One succeeds, one fails</td>
<td><span class="math inline">\(2P(1-P) = 0.32\)</span></td>
<td><span class="math inline">\(f + 1\)</span></td>
</tr>
<tr class="odd">
<td>Both fail</td>
<td><span class="math inline">\((1-P)^2 = 0.04\)</span></td>
<td><span class="math inline">\(2\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="setting-the-deposit-rate" class="level4" data-number="5.3.8.2">
<h4 data-number="5.3.8.2" class="anchored" data-anchor-id="setting-the-deposit-rate"><span class="header-section-number">5.3.8.2</span> Setting the Deposit Rate</h4>
<p>The bank issues total deposits with face value <span class="math inline">\(2B\)</span>. If <span class="math inline">\(f\)</span> is set large enough that <span class="math inline">\(f + 1 \geq 2B\)</span>, the bank repays depositors whenever <strong>at most one borrower defaults</strong>. The bank fails only when <strong>both fail simultaneously</strong> — probability <span class="math inline">\((1-P)^2 = 0.04\)</span>.</p>
<p>Depositor break-even:</p>
<p><span class="math display">\[\Pr(\text{bank pays}) \times 2B = 2r\]</span> <span class="math display">\[0.96 \times 2B = 2(1.05) = 2.10\]</span> <span class="math display">\[2B = 2.1875 \quad \Rightarrow \quad B = 1.09375\]</span></p>
<p><strong>Deposit rate = 9.375%</strong> — above the 5% risk-free rate, compensating for the 4% residual failure probability.</p>
</section>
<section id="setting-the-loan-rate" class="level4" data-number="5.3.8.3">
<h4 data-number="5.3.8.3" class="anchored" data-anchor-id="setting-the-loan-rate"><span class="header-section-number">5.3.8.3</span> Setting the Loan Rate</h4>
<p>For the bank to pay <span class="math inline">\(2B = 2.1875\)</span> when exactly one borrower defaults:</p>
<p><span class="math display">\[f + 1 \geq 2B = 2.1875 \quad \Rightarrow \quad f \geq 1.1875\]</span></p>
<p>Setting <span class="math inline">\(f = 1.1875\)</span> (minimum viable face value):</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Two-Loan Bank: Complete Numerical Example
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table-striped caption-top table">
<caption>Two-loan bank outcome table</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Prob</th>
<th>Bank income</th>
<th>Deposits owed</th>
<th>Bank pays</th>
<th>Banker keeps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Both succeed</td>
<td>0.64</td>
<td><span class="math inline">\(2(1.1875) = 2.375\)</span></td>
<td>2.1875</td>
<td>2.1875 ✓</td>
<td><strong>0.1875</strong></td>
</tr>
<tr class="even">
<td>One succeeds, one fails</td>
<td>0.32</td>
<td><span class="math inline">\(1.1875 + 1 = 2.1875\)</span></td>
<td>2.1875</td>
<td>2.1875 ✓</td>
<td><strong>0</strong></td>
</tr>
<tr class="odd">
<td>Both fail</td>
<td>0.04</td>
<td><span class="math inline">\(2\)</span></td>
<td>2.1875</td>
<td><strong>0</strong> (bank liquidated)</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>Depositor expected return: <span class="math inline">\(0.96 \times 2.1875 = 2.10 = 2 \times 1.05\)</span> ✓</p>
<ul>
<li><strong>Loan rate = 18.75%</strong> (face value <span class="math inline">\(f = 1.1875\)</span>)</li>
<li><strong>Deposit rate = 9.375%</strong> (<span class="math inline">\(B = 1.09375\)</span>)</li>
<li><strong>Bank failure probability = 4%</strong> (down from 20% for a one-loan bank)</li>
</ul>
</div>
</div>
</section>
<section id="monitoring-incentive-will-the-banker-monitor" class="level4" data-number="5.3.8.4">
<h4 data-number="5.3.8.4" class="anchored" data-anchor-id="monitoring-incentive-will-the-banker-monitor"><span class="header-section-number">5.3.8.4</span> Monitoring Incentive: Will the Banker Monitor?</h4>
<p>The banker earns a profit only when neither borrower defaults (probability 0.64), getting <span class="math inline">\(2.375 - 2.1875 = 0.1875\)</span>. Expected banker profit = <span class="math inline">\(0.64 \times 0.1875 \approx 0.12\)</span>.</p>
<p>Since <span class="math inline">\(0.12 \gg 2K = 0.0004\)</span> (the monitoring cost for two loans), the banker will indeed monitor. The banker earns a <strong>control rent</strong> — above-normal profits that align incentives with depositors. Diamond (1996) calculates this carefully as approximately <span class="math inline">\(0.0608\)</span> per borrower.</p>
</section>
<section id="the-delegation-cost" class="level4" data-number="5.3.8.5">
<h4 data-number="5.3.8.5" class="anchored" data-anchor-id="the-delegation-cost"><span class="header-section-number">5.3.8.5</span> The Delegation Cost</h4>
<p>The total delegation cost <span class="math inline">\(D\)</span> per borrower consists of two components:</p>
<p><strong>Component 1 — Financial distress:</strong> When both borrowers default (prob 0.04), the bank is liquidated and assets worth 2 are destroyed: <span class="math display">\[\text{Distress cost} = 0.04 \times 2 = 0.08\]</span></p>
<p><strong>Component 2 — Control rent:</strong> The banker must earn above-normal profits to have incentives to monitor: <span class="math display">\[\text{Control rent} \approx 0.0608\]</span></p>
<p><span class="math display">\[D = \underbrace{0.08}_{\text{distress}} + \underbrace{0.0608}_{\text{control rent}} = 0.1408\]</span></p>
<p><span class="math display">\[\boxed{K + D = 0.0002 + 0.1408 = 0.141}\]</span></p>
</section>
</section>
<section id="three-arrangements-compared" class="level3" data-number="5.3.9">
<h3 data-number="5.3.9" class="anchored" data-anchor-id="three-arrangements-compared"><span class="header-section-number">5.3.9</span> Three Arrangements Compared</h3>
<p>Diamond (1996) identifies three arrangements and their total costs:</p>
<div style="margin: 20px 0;">
  <svg width="600" height="260" viewbox="0 0 600 260" style="margin: 0 auto; display: block; font-family: serif;">
    <text x="300" y="18" font-size="13" font-weight="bold" text-anchor="middle">Three Contracting Arrangements: Cost Comparison</text>
    <!-- Option 1 -->
    <rect x="15" y="30" width="175" height="195" rx="6" fill="#fff3e0" stroke="#e65100" stroke-width="2"></rect>
    <text x="103" y="50" font-size="11" font-weight="bold" text-anchor="middle" fill="#bf360c">(1) No Monitoring</text>
    <text x="103" y="68" font-size="10" text-anchor="middle">Widely-held unmonitored debt</text>
    <text x="103" y="83" font-size="10" text-anchor="middle">Face value: f = 1.3125</text>
    <line x1="28" y1="93" x2="177" y2="93" stroke="#e65100" stroke-width="1" stroke-dasharray="3,2"></line>
    <text x="103" y="113" font-size="13" font-weight="bold" text-anchor="middle" fill="#e65100">Cost = S = 0.2</text>
    <text x="103" y="133" font-size="10" text-anchor="middle">(liquidation waste when</text>
    <text x="103" y="147" font-size="10" text-anchor="middle">V = L = 1)</text>
    <rect x="28" y="160" width="148" height="50" rx="4" fill="#ffe0b2" stroke="#e65100" stroke-width="1"></rect>
    <text x="103" y="179" font-size="10" text-anchor="middle" fill="#bf360c">Loan rate = 31.25%</text>
    <text x="103" y="197" font-size="10" text-anchor="middle" fill="#bf360c">No monitoring effort</text>
    <!-- Option 2 -->
    <rect x="213" y="30" width="175" height="195" rx="6" fill="#fce4ec" stroke="#c62828" stroke-width="2"></rect>
    <text x="301" y="50" font-size="11" font-weight="bold" text-anchor="middle" fill="#b71c1c">(2) Direct Monitoring</text>
    <text x="301" y="68" font-size="10" text-anchor="middle">All m investors monitor;</text>
    <text x="301" y="83" font-size="10" text-anchor="middle">face f ≈ 1.0625</text>
    <line x1="225" y1="93" x2="375" y2="93" stroke="#c62828" stroke-width="1" stroke-dasharray="3,2"></line>
    <text x="301" y="113" font-size="13" font-weight="bold" text-anchor="middle" fill="#c62828">Cost = mK = 2</text>
    <text x="301" y="133" font-size="10" text-anchor="middle">(prohibitive — exceeds</text>
    <text x="301" y="147" font-size="10" text-anchor="middle">project value of 1.32!)</text>
    <rect x="225" y="160" width="148" height="50" rx="4" fill="#ffcdd2" stroke="#c62828" stroke-width="1"></rect>
    <text x="301" y="179" font-size="10" text-anchor="middle" fill="#b71c1c">Loan rate ≈ 6.25%</text>
    <text x="301" y="197" font-size="10" text-anchor="middle" fill="#b71c1c">But mK = 2 &gt;&gt; S = 0.2</text>
    <!-- Option 3 -->
    <rect x="412" y="30" width="175" height="195" rx="6" fill="#e8f5e9" stroke="#2e7d32" stroke-width="2"></rect>
    <text x="500" y="50" font-size="11" font-weight="bold" text-anchor="middle" fill="#1b5e20">(3) Delegated Monitoring</text>
    <text x="500" y="68" font-size="10" text-anchor="middle">Bank monitors; depositors</text>
    <text x="500" y="83" font-size="10" text-anchor="middle">face B = 1.09375</text>
    <line x1="425" y1="93" x2="574" y2="93" stroke="#2e7d32" stroke-width="1" stroke-dasharray="3,2"></line>
    <text x="500" y="113" font-size="13" font-weight="bold" text-anchor="middle" fill="#2e7d32">Cost = K+D = 0.141</text>
    <text x="500" y="133" font-size="10" text-anchor="middle">(saves distress 0.2</text>
    <text x="500" y="147" font-size="10" text-anchor="middle">at cost 0.141 &lt; 0.2)</text>
    <rect x="425" y="160" width="148" height="50" rx="4" fill="#c8e6c9" stroke="#2e7d32" stroke-width="1"></rect>
    <text x="500" y="179" font-size="10" text-anchor="middle" fill="#1b5e20">Loan rate = 18.75%</text>
    <text x="500" y="197" font-size="10" text-anchor="middle" fill="#1b5e20">Net gain = 0.059 &gt; 0 ✓</text>
    <text x="300" y="246" font-size="11" text-anchor="middle" fill="#333" font-style="italic">Delegated monitoring dominates: K + D = 0.141 &lt; S = 0.2 &lt; mK = 2</text>
  </svg>
</div>
<table class="table-striped caption-top table">
<caption>Summary: total cost per borrower (Diamond 1996)</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Arrangement</th>
<th>Cost</th>
<th>Net gain vs.&nbsp;(1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(1) No monitoring (unmonitored debt, <span class="math inline">\(f = 1.3125\)</span>)</td>
<td><span class="math inline">\(S = 0.200\)</span></td>
<td>—</td>
</tr>
<tr class="even">
<td>(2) Direct monitoring (all <span class="math inline">\(m\)</span> investors)</td>
<td><span class="math inline">\(mK = 2.000\)</span></td>
<td><span class="math inline">\(-1.800\)</span></td>
</tr>
<tr class="odd">
<td>(3) Two-loan bank (<span class="math inline">\(n = 2\)</span>)</td>
<td><span class="math inline">\(K + D = 0.141\)</span></td>
<td><span class="math inline">\(+0.059\)</span></td>
</tr>
<tr class="even">
<td>Fully diversified bank (<span class="math inline">\(n \to \infty\)</span>)</td>
<td><span class="math inline">\(K = 0.0002\)</span></td>
<td><span class="math inline">\(+0.200\)</span></td>
</tr>
</tbody>
</table>
<p>Option (3) strictly dominates both (1) and (2). The two-loan bank saves <span class="math inline">\(0.2 - 0.141 = 0.059\)</span> per borrower. The key condition for delegation to dominate:</p>
<p><span class="math display">\[K + D &lt; \min(S,\; m \times K)\]</span> <span class="math display">\[0.141 &lt; \min(0.2,\; 2) = 0.2 \quad \checkmark\]</span></p>
</section>
<section id="the-n-loan-bank" class="level3" data-number="5.3.10">
<h3 data-number="5.3.10" class="anchored" data-anchor-id="the-n-loan-bank"><span class="header-section-number">5.3.10</span> The <span class="math inline">\(n\)</span>-Loan Bank</h3>
<section id="the-law-of-large-numbers" class="level4" data-number="5.3.10.1">
<h4 data-number="5.3.10.1" class="anchored" data-anchor-id="the-law-of-large-numbers"><span class="header-section-number">5.3.10.1</span> The Law of Large Numbers</h4>
<p>With <span class="math inline">\(n\)</span> independent loans (each returning <span class="math inline">\(f\)</span> with prob <span class="math inline">\(P\)</span> and <span class="math inline">\(1\)</span> with prob <span class="math inline">\(1-P\)</span>), the number of successes <span class="math inline">\(S_n \sim \text{Binomial}(n, P)\)</span>. By the Law of Large Numbers:</p>
<p><span class="math display">\[\frac{S_n}{n} \xrightarrow{\text{a.s.}} P = 0.8 \quad \text{as } n \to \infty\]</span></p>
<p>The bank’s income per loan converges to <span class="math inline">\(P \times f + (1-P) \times 1 = 0.8f + 0.2\)</span> almost surely. For <span class="math inline">\(f &gt; 1.0625\)</span>, this exceeds the deposit rate <span class="math inline">\(B\)</span>, so the bank almost always pays depositors. Bank failure probability <span class="math inline">\(\to 0\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Main Result (Diamond 1984, 1996)
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the limit of a <strong>perfectly diversified bank</strong> with <span class="math inline">\(n \to \infty\)</span> independent loans:</p>
<p><span class="math display">\[D(n) \to 0, \quad K + D(n) \to K = 0.0002\]</span></p>
<ul>
<li><strong>Deposit rate <span class="math inline">\(\to r = 5\%\)</span></strong> (the risk-free rate)</li>
<li><strong>Loan face value <span class="math inline">\(f \to 1.06275\)</span></strong> (solution to <span class="math inline">\(0.8f + 0.2 = 1.05 + K\)</span>)</li>
<li><strong>Borrowers’ expected cost of capital <span class="math inline">\(\to 5.02\%\)</span></strong> (just above the risk-free rate)</li>
</ul>
<p>All distress costs are eliminated. The full surplus <span class="math inline">\(S - K = 0.2 - 0.0002 = 0.1998\)</span> per borrower is available to borrowers and depositors.</p>
</div>
</div>
<div style="margin: 20px 0;">
  <svg width="560" height="310" viewbox="0 0 560 310" style="margin: 0 auto; display: block; font-family: serif;">
    <defs>
      <marker id="arr-n2" markerwidth="10" markerheight="10" refx="9" refy="3" orient="auto">
        <path d="M0,0 L0,6 L9,3 z" fill="black"></path>
      </marker>
    </defs>
    <line x1="70" y1="255" x2="510" y2="255" stroke="black" stroke-width="1.5" marker-end="url(#arr-n2)"></line>
    <text x="520" y="260" font-size="12" font-style="italic">n</text>
    <text x="290" y="293" font-size="12" text-anchor="middle">Number of loans (n)</text>
    <line x1="70" y1="265" x2="70" y2="28" stroke="black" stroke-width="1.5" marker-end="url(#arr-n2)"></line>
    <text x="18" y="148" font-size="10" text-anchor="middle" transform="rotate(-90 18 148)">Cost per borrower</text>
    <!-- Y axis labels -->
    <line x1="65" y1="55" x2="75" y2="55" stroke="black" stroke-width="1"></line>
    <text x="60" y="59" font-size="10" text-anchor="end">2.0 (mK)</text>
    <line x1="65" y1="128" x2="75" y2="128" stroke="black" stroke-width="1"></line>
    <text x="60" y="132" font-size="10" text-anchor="end">0.2 (S)</text>
    <line x1="65" y1="163" x2="75" y2="163" stroke="black" stroke-width="1"></line>
    <text x="60" y="167" font-size="10" text-anchor="end">0.14</text>
    <line x1="65" y1="251" x2="75" y2="251" stroke="black" stroke-width="1"></line>
    <text x="60" y="255" font-size="10" text-anchor="end">≈0 (K)</text>
    <!-- x-axis ticks -->
    <line x1="100" y1="250" x2="100" y2="260" stroke="black" stroke-width="1"></line>
    <text x="100" y="274" font-size="10" text-anchor="middle">1</text>
    <line x1="155" y1="250" x2="155" y2="260" stroke="black" stroke-width="1"></line>
    <text x="155" y="274" font-size="10" text-anchor="middle">2</text>
    <!-- mK dashed red -->
    <line x1="70" y1="55" x2="500" y2="55" stroke="red" stroke-width="1.5" stroke-dasharray="8,4"></line>
    <text x="430" y="47" font-size="10" fill="red" font-weight="bold">Direct: mK = 2</text>
    <!-- S dashed orange -->
    <line x1="70" y1="128" x2="500" y2="128" stroke="#e65100" stroke-width="1.5" stroke-dasharray="6,3"></line>
    <text x="395" y="121" font-size="10" fill="#e65100" font-weight="bold">No monitoring: S = 0.2</text>
    <!-- K+D(n) curve: at n=1 = 0.2, at n=2 = 0.141, falls toward K≈0 -->
    <polyline points="100,128 130,139 155,149 185,159 220,168 255,177 295,185 340,193 385,200 430,205 475,210 500,213" fill="none" stroke="#ff8800" stroke-width="2.5"></polyline>
    <!-- n=1 point -->
    <circle cx="100" cy="128" r="4" fill="#888"></circle>
    <text x="75" y="122" font-size="8" fill="#666">n=1: K+D≈S</text>
    <!-- n=2 point -->
    <circle cx="155" cy="149" r="5" fill="#ff8800"></circle>
    <line x1="155" y1="149" x2="155" y2="163" stroke="#ff8800" stroke-width="1" stroke-dasharray="3,2"></line>
    <text x="174" y="146" font-size="10" fill="#cc6600" font-weight="bold">n=2: K+D = 0.141 &lt; S</text>
    <!-- Asymptote K≈0 -->
    <line x1="70" y1="251" x2="500" y2="251" stroke="green" stroke-width="1.5" stroke-dasharray="5,3"></line>
    <text x="365" y="245" font-size="10" fill="green" font-weight="bold">→ K = 0.0002 as n→∞</text>
    <!-- Curve label -->
    <text x="345" y="188" font-size="11" fill="#cc6600" font-weight="bold">K + D(n)</text>
    <!-- Shaded region -->
    <rect x="70" y="213" width="430" height="38" fill="green" fill-opacity="0.08"></rect>
    <text x="285" y="236" font-size="9" text-anchor="middle" fill="#2e7d32">Delegation beats no monitoring: K + D &lt; S</text>
  </svg>
</div>
<p><strong>Figure</strong> (adapted from Diamond 1996). Total intermediation cost per borrower as a function of bank size <span class="math inline">\(n\)</span>. At <span class="math inline">\(n = 1\)</span>, delegation achieves no efficiency gain. At <span class="math inline">\(n = 2\)</span>, <span class="math inline">\(K + D = 0.141 &lt; S = 0.2\)</span> and delegation becomes worthwhile. As <span class="math inline">\(n \to \infty\)</span>, total cost converges to the irreducible monitoring cost <span class="math inline">\(K = 0.0002\)</span>.</p>
</section>
</section>
<section id="the-formal-diamond-1984-model" class="level3" data-number="5.3.11">
<h3 data-number="5.3.11" class="anchored" data-anchor-id="the-formal-diamond-1984-model"><span class="header-section-number">5.3.11</span> The Formal Diamond (1984) Model</h3>
<p>The Diamond (1996) analysis uses a binary distribution (<span class="math inline">\(V_j \in \{L, H\}\)</span>) to build concrete intuition. Diamond (1984) proves the same results in a fully general setting. This section presents the formal model, showing that the binary example is a special case and that the limit result <span class="math inline">\(D(n) \to 0\)</span> holds under mild regularity conditions.</p>
<section id="general-environment" class="level4" data-number="5.3.11.1">
<h4 data-number="5.3.11.1" class="anchored" data-anchor-id="general-environment"><span class="header-section-number">5.3.11.1</span> General Environment</h4>
<p>All notation carries over from the binary setup. The only change is to replace the two-point distribution with a general one.</p>
<p><strong>Borrowers</strong>: <span class="math inline">\(n\)</span> borrowers, each requiring 1 unit of capital. Borrower <span class="math inline">\(j\)</span>’s project return <span class="math inline">\(V_j\)</span> is drawn <strong>i.i.d.</strong> from a distribution with c.d.f. <span class="math inline">\(G(\cdot)\)</span> on support <span class="math inline">\([V_{\min}, V_{\max}]\)</span> and mean <span class="math inline">\(\mu = \mathbb{E}[V_j]\)</span>. Only the borrower observes the realized <span class="math inline">\(V_j\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Connecting General and Binary
</div>
</div>
<div class="callout-body-container callout-body">
<p>The binary Diamond (1996) case is the special case <span class="math inline">\(G(v) = (1-P)\cdot\mathbf{1}(v \geq L) + 1 \cdot \mathbf{1}(v \geq H)\)</span>, so that <span class="math inline">\(G(f)= \Pr(V_j &lt; f) = 1-P = 0.2\)</span> for <span class="math inline">\(L \leq f \leq H\)</span>. All formulas below reduce exactly to the numerical examples when this is substituted.</p>
</div>
</div>
<p><strong>Depositors</strong>: <span class="math inline">\(m \cdot n\)</span> depositors, each contributing <span class="math inline">\(1/m\)</span>. The bank promises each depositor a gross return of <span class="math inline">\(B\)</span> per unit deposited. Total deposit obligation = <span class="math inline">\(nB\)</span>.</p>
<p><strong>Monitoring cost</strong>: <span class="math inline">\(K &gt; 0\)</span> per loan. Monitoring allows the bank to observe the true <span class="math inline">\(V_j\)</span> and collect it in default states rather than liquidating.</p>
</section>
<section id="the-banks-per-loan-income" class="level4" data-number="5.3.11.2">
<h4 data-number="5.3.11.2" class="anchored" data-anchor-id="the-banks-per-loan-income"><span class="header-section-number">5.3.11.2</span> The Bank’s Per-Loan Income</h4>
<p>The bank holds the Gale-Hellwig optimal loan contract (face value <span class="math inline">\(f\)</span>) on each of its <span class="math inline">\(n\)</span> loans. Using the CSV framework from above:</p>
<p><span class="math display">\[
R_j \;=\; \underbrace{f \cdot \mathbf{1}(V_j \geq f)}_{\text{good state: borrower pays }f} + \underbrace{V_j \cdot \mathbf{1}(V_j &lt; f)}_{\text{bad state: bank monitors, collects }V_j} - \underbrace{K \cdot \mathbf{1}(V_j &lt; f)}_{\text{monitoring cost}}
\]</span></p>
<p>This can be written compactly as <span class="math inline">\(R_j = \min(V_j,\, f) - K \cdot \mathbf{1}(V_j &lt; f)\)</span>.</p>
<p><strong>Expected per-loan income</strong>:</p>
<p><span class="math display">\[
\rho \;\equiv\; \mathbb{E}[R_j] = \mathbb{E}[\min(V_j, f)] - K \cdot G(f)
\]</span></p>
<p>where <span class="math inline">\(G(f) = \Pr(V_j &lt; f)\)</span> is the default probability.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Binary Special Case
</div>
</div>
<div class="callout-body-container callout-body">
<p>With <span class="math inline">\(V_j \in \{L, H\}\)</span> and <span class="math inline">\(f \in (L, H)\)</span>: <span class="math inline">\(G(f) = 1 - P\)</span>, <span class="math inline">\(\mathbb{E}[\min(V_j, f)] = P \cdot f + (1-P) \cdot L\)</span>, so</p>
<p><span class="math display">\[\rho = Pf + (1-P)L - (1-P)K = Pf + (1-P)(L-K)\]</span></p>
<p>This is exactly the formula used to set the two-loan bank’s deposit rate.</p>
</div>
</div>
<p><strong>Bank’s total income</strong> across <span class="math inline">\(n\)</span> loans:</p>
<p><span class="math display">\[W_n = \sum_{j=1}^n R_j\]</span></p>
<p>Since <span class="math inline">\(R_1, \ldots, R_n\)</span> are i.i.d. with mean <span class="math inline">\(\rho\)</span> and finite variance <span class="math inline">\(\sigma^2 = \text{Var}(R_j) &lt; \infty\)</span>, the Law of Large Numbers gives:</p>
<p><span class="math display">\[\frac{W_n}{n} \xrightarrow{a.s.} \rho \quad \text{as } n \to \infty\]</span></p>
</section>
<section id="the-delegation-contract" class="level4" data-number="5.3.11.3">
<h4 data-number="5.3.11.3" class="anchored" data-anchor-id="the-delegation-contract"><span class="header-section-number">5.3.11.3</span> The Delegation Contract</h4>
<p>The bank issues <strong>fixed-rate deposits</strong> with face value <span class="math inline">\(B\)</span> per unit (total promise <span class="math inline">\(nB\)</span>). This is the Gale-Hellwig optimal contract applied to the bank-depositor relationship: monitor the bank only in the (rare) event it fails to pay. In Diamond (1984), these contracts take the form of <strong>non-random penalties</strong> (NRP) — a schedule of non-pecuniary utility penalties <span class="math inline">\(h(x)\)</span> triggered when the bank’s total payment <span class="math inline">\(x\)</span> falls below the promised <span class="math inline">\(nB\)</span>:</p>
<p><span class="math display">\[h(x) = 0 \;\text{ if } x \geq nB, \qquad h(x) &gt; 0 \;\text{ if } x &lt; nB\]</span></p>
<p>The penalties are deterministic (non-random) conditional on <span class="math inline">\(x\)</span>, which is optimal — randomization would be wasteful. In Diamond (1996), this is simplified to the liquidation threat used throughout: if the bank pays less than <span class="math inline">\(nB\)</span>, depositors liquidate and everyone gets 0.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
NRP vs.&nbsp;Liquidation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The NRP contract and the liquidation contract converge for large <span class="math inline">\(n\)</span>: in both cases the bank almost always pays <span class="math inline">\(nB\)</span> in full, so the penalty mechanism is almost never triggered. The formal Diamond (1984) model uses NRP because it is more general; the liquidation simplification in Diamond (1996) is equivalent in the limit and easier to analyze with small <span class="math inline">\(n\)</span>.</p>
</div>
</div>
<p><strong>Bank failure</strong>: The bank fails to meet its deposit obligation when <span class="math inline">\(W_n &lt; nB\)</span>, i.e., when the per-loan average income falls below the promised deposit rate:</p>
<p><span class="math display">\[\Pr(\text{bank fails}) = \Pr\!\left(\frac{W_n}{n} &lt; B\right)\]</span></p>
</section>
<section id="main-theorem" class="level4" data-number="5.3.11.4">
<h4 data-number="5.3.11.4" class="anchored" data-anchor-id="main-theorem"><span class="header-section-number">5.3.11.4</span> Main Theorem</h4>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Theorem (Diamond 1984): Delegation Cost Vanishes with Diversification
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(R_1, R_2, \ldots\)</span> be i.i.d. loan returns with mean <span class="math inline">\(\rho\)</span> and variance <span class="math inline">\(\sigma^2 &lt; \infty\)</span>. Suppose the face value <span class="math inline">\(f\)</span> and deposit rate <span class="math inline">\(B\)</span> satisfy <span class="math inline">\(B &lt; \rho\)</span> (the bank earns strictly more per loan than it owes per deposit, leaving a positive control rent). Then the delegation cost per borrower satisfies:</p>
<p><span class="math display">\[D(n) \to 0 \quad \text{as } n \to \infty\]</span></p>
<p>and the total intermediation cost converges to the irreducible monitoring cost:</p>
<p><span class="math display">\[K + D(n) \to K \quad \text{as } n \to \infty\]</span></p>
<p>In the limit: deposit rate <span class="math inline">\(B \to r\)</span>, loan face value <span class="math inline">\(f \to f \approx 1.0625\)</span> (the Gale-Hellwig CSV-optimal value), and the full social surplus <span class="math inline">\(\mu - r - K\)</span> per project is distributed between borrowers and depositors.</p>
</div>
</div>
<p><strong>Proof sketch via Chebyshev’s inequality</strong>. The delegation cost arises from two sources: (i) financial distress when <span class="math inline">\(W_n &lt; nB\)</span>, and (ii) the control rent required to keep <span class="math inline">\(B &lt; \rho\)</span>. For the distress component, apply Chebyshev to the sample mean:</p>
<p><span class="math display">\[\Pr\!\left(\frac{W_n}{n} &lt; B\right) = \Pr\!\left(\frac{W_n}{n} - \rho &lt; -({\rho - B})\right) \leq \Pr\!\left(\left|\frac{W_n}{n} - \rho\right| \geq \rho - B\right) \leq \frac{\sigma^2}{n(\rho - B)^2}\]</span></p>
<p>The bank failure probability is <span class="math inline">\(O(1/n)\)</span>. Since the value destroyed in failure is bounded, the financial distress component of <span class="math inline">\(D(n)\)</span> is <span class="math inline">\(O(1/n) \to 0\)</span>.</p>
<p>For the control rent: as <span class="math inline">\(n\)</span> grows, the bank almost surely pays depositors in full, so the minimum rent needed to align incentives shrinks toward zero. Diamond (1984) shows the required rent is proportional to the failure probability, so it too is <span class="math inline">\(O(1/n)\)</span>.</p>
<p>Both components vanish, giving <span class="math inline">\(D(n) \to 0\)</span>. <span class="math inline">\(\square\)</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Binary Special Case: Chebyshev Bound
</div>
</div>
<div class="callout-body-container callout-body">
<p>With <span class="math inline">\(V_j \in \{L, H\}\)</span> and the two-loan bank (<span class="math inline">\(n=2\)</span>): <span class="math inline">\(\sigma^2 = P(1-P)(f-L+K)^2\)</span>. For <span class="math inline">\(f=1.1875\)</span>, <span class="math inline">\(B = 1.09375\)</span>, <span class="math inline">\(\rho = 0.8(1.1875)+0.2(1-0.0002) = 1.15\)</span>, and <span class="math inline">\(\rho - B = 0.05625\)</span>:</p>
<p><span class="math display">\[\Pr(\text{bank fails}) \leq \frac{\sigma^2}{2(0.05625)^2}\]</span></p>
<p>The Chebyshev bound is conservative; the exact binomial gives <span class="math inline">\((1-P)^2 = 0.04\)</span> for <span class="math inline">\(n=2\)</span>, approaching 0 geometrically as <span class="math inline">\(n\)</span> grows.</p>
</div>
</div>
</section>
<section id="debt-is-optimal-on-both-sides" class="level4" data-number="5.3.11.5">
<h4 data-number="5.3.11.5" class="anchored" data-anchor-id="debt-is-optimal-on-both-sides"><span class="header-section-number">5.3.11.5</span> Debt Is Optimal on Both Sides</h4>
<p>A central result of Diamond (1984) is that the <strong>same CSV logic</strong> that makes debt optimal on the asset side (Gale-Hellwig 1985) also makes debt optimal on the liability side. The bank simultaneously applies the Gale-Hellwig principle in two relationships:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Relationship</th>
<th>CSV problem</th>
<th>Optimal contract</th>
<th>When monitoring occurs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bank → Borrower</strong></td>
<td>Borrower hides <span class="math inline">\(V_j\)</span></td>
<td>Loan at face value <span class="math inline">\(f\)</span>; monitor in default</td>
<td>When <span class="math inline">\(V_j &lt; f\)</span>; prob <span class="math inline">\(G(f)\)</span> per loan</td>
</tr>
<tr class="even">
<td><strong>Depositor → Bank</strong></td>
<td>Bank hides portfolio income <span class="math inline">\(W_n\)</span></td>
<td>Deposit at face value <span class="math inline">\(B\)</span>; liquidate in failure</td>
<td>When <span class="math inline">\(W_n &lt; nB\)</span>; prob <span class="math inline">\(O(1/n) \to 0\)</span></td>
</tr>
</tbody>
</table>
<p>The key asymmetry: on the asset side, each loan defaults with probability <span class="math inline">\(G(f) \approx 0.2\)</span> (the irreducible credit risk of individual loans). On the liability side, the bank fails with probability <span class="math inline">\(O(1/n)\)</span>, which the bank itself controls by diversifying. Diversification makes the liability side of the bank’s balance sheet <strong>nearly riskless</strong> even though each individual loan is risky.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The Transformation the Bank Performs
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\underbrace{\text{Monitored loans}}_{\text{risky, monitoring-intensive}} \xrightarrow{\;\text{diversification}\;} \underbrace{\text{Fixed-rate deposits}}_{\text{nearly riskless, monitoring-free}}\]</span></p>
<p>This transformation is the core function of financial intermediation in Diamond (1984). The bank <strong>converts information-intensive, individually risky assets into nearly riskless liabilities</strong> by pooling independently distributed credit risk. No other institution — not a mutual fund, not a bond market — achieves this automatically, because doing so requires the monitoring expertise and diversification that only a bank provides.</p>
</div>
</div>
</section>
</section>
<section id="what-makes-a-good-bank" class="level3" data-number="5.3.12">
<h3 data-number="5.3.12" class="anchored" data-anchor-id="what-makes-a-good-bank"><span class="header-section-number">5.3.12</span> What Makes a Good Bank?</h3>
<section id="diversification-is-essential-not-optional" class="level4" data-number="5.3.12.1">
<h4 data-number="5.3.12.1" class="anchored" data-anchor-id="diversification-is-essential-not-optional"><span class="header-section-number">5.3.12.1</span> Diversification Is Essential, Not Optional</h4>
<p>Diamond (1996): “Diversification makes bank deposits much safer than bank loans, and in the limit of fully diversified banks with independently distributed loans, bank deposits become riskless.”</p>
<p>An <strong>undiversified</strong> bank: fails frequently, requires high deposit rates, needs large control rents, provides little efficiency gain.</p>
<p>A <strong>well-diversified</strong> bank: rarely fails, deposits approach risklessness, loan rates approach the monitored rate, captures nearly the full surplus <span class="math inline">\(S\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Concentration Risk Is Directly Costly
</div>
</div>
<div class="callout-body-container callout-body">
<p>Undiversification is not merely riskier — it is <strong>more expensive</strong>. Banks with concentrated loan portfolios:</p>
<ol type="1">
<li>Have higher financial distress probability → higher delegation costs</li>
<li>Require higher control rents → pass costs to borrowers</li>
<li>Cannot approach the efficiency of the fully diversified limit</li>
</ol>
<p>This provides a clear theoretical foundation for <strong>concentration limits and large-exposure rules</strong>: they are not just risk-management tools but efficiency requirements rooted in the Diamond mechanism.</p>
</div>
</div>
</section>
<section id="debt-is-the-natural-liability-of-banks" class="level4" data-number="5.3.12.2">
<h4 data-number="5.3.12.2" class="anchored" data-anchor-id="debt-is-the-natural-liability-of-banks"><span class="header-section-number">5.3.12.2</span> Debt Is the Natural Liability of Banks</h4>
<p>The model derives (not assumes) that banks issue fixed-rate deposits. Debt minimizes depositor monitoring:</p>
<ul>
<li><strong>Good states</strong> (bank income <span class="math inline">\(\geq 2B\)</span>): Bank pays <span class="math inline">\(2B\)</span> voluntarily; no monitoring needed</li>
<li><strong>Bad states</strong> (bank income <span class="math inline">\(&lt; 2B\)</span>): Liquidation enforces payment; rare when bank is diversified</li>
</ul>
<p>Any variable (equity-like) payment would require depositors to observe bank income in every period. Debt confines monitoring to rare default states. The bank <strong>transforms monitored debt (loans) into unmonitored debt (deposits)</strong> through diversification.</p>
</section>
<section id="banks-should-hedge-non-monitoring-risks" class="level4" data-number="5.3.12.3">
<h4 data-number="5.3.12.3" class="anchored" data-anchor-id="banks-should-hedge-non-monitoring-risks"><span class="header-section-number">5.3.12.3</span> Banks Should Hedge Non-Monitoring Risks</h4>
<p>Because the bank’s value comes from its monitoring expertise, bearing risks unrelated to monitoring undermines efficiency. Diamond (1996):</p>
<blockquote class="blockquote">
<p>“There is no incentive reason for the bank to bear general interest rate risk. The bank’s high leverage means that a small loss might force a costly default. Hedging of interest rate risk is desirable… unless a risk is intimately related to their monitoring task, banks should avoid risks that are not diversifiable.”</p>
</blockquote>
<p>Banks should hedge interest rate risk not because they are risk-averse but because increased distress probability raises delegation costs directly. This insight applies to Silicon Valley Bank (2023), which chose to bear large unhedged interest rate risk on long-term securities — precisely the kind of non-monitoring risk Diamond warns against.</p>
</section>
<section id="non-diversifiable-risk-limits-the-efficiency-gains" class="level4" data-number="5.3.12.4">
<h4 data-number="5.3.12.4" class="anchored" data-anchor-id="non-diversifiable-risk-limits-the-efficiency-gains"><span class="header-section-number">5.3.12.4</span> Non-Diversifiable Risk Limits the Efficiency Gains</h4>
<p>The model requires loan returns to be <strong>independent</strong>. When returns are correlated (recessions, regional shocks, industry cycles):</p>
<ul>
<li>The bank’s income does not converge to its mean for large <span class="math inline">\(n\)</span></li>
<li>Delegation costs remain positive even with many loans</li>
<li>Financial distress and control rents are higher</li>
</ul>
<p>Diamond (1996): “This is too strong because in practice the default risk of borrowers is not independent, it is positively correlated.” This is why systemic banking crises — where many banks fail simultaneously — are so costly: correlation failures cannot be diversified away at the individual bank level.</p>
</section>
</section>
<section id="the-asset-and-liability-sides-together" class="level3" data-number="5.3.13">
<h3 data-number="5.3.13" class="anchored" data-anchor-id="the-asset-and-liability-sides-together"><span class="header-section-number">5.3.13</span> The Asset and Liability Sides Together</h3>
<p>Diamond (1984, 1996) provides the asset-side justification for banking; Diamond and Dybvig (1983) provides the liability-side justification. Together, they explain the full structure of the commercial bank balance sheet:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 37%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Liability side (DD 1983)</th>
<th>Asset side (Diamond 1984, 1996)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Core problem</strong></td>
<td>Timing uncertainty / liquidity need</td>
<td>Borrower moral hazard</td>
</tr>
<tr class="even">
<td><strong>Bank’s role</strong></td>
<td>Liquidity transformation</td>
<td>Delegated monitoring</td>
</tr>
<tr class="odd">
<td><strong>Key mechanism</strong></td>
<td>Pool idiosyncratic liquidity shocks</td>
<td>Diversify idiosyncratic default risk</td>
</tr>
<tr class="even">
<td><strong>Why deposits are debt</strong></td>
<td>Optimal with sequential service</td>
<td>Minimizes depositor monitoring</td>
</tr>
<tr class="odd">
<td><strong>Why hold many loans</strong></td>
<td>Less relevant</td>
<td>Essential: LLN reduces delegation cost</td>
</tr>
<tr class="even">
<td><strong>Source of fragility</strong></td>
<td>Coordination failure / run</td>
<td>Correlated loan losses / undiversification</td>
</tr>
</tbody>
</table>
<p>Both theories predict the same institutional form: a bank that holds illiquid, diversified loans and issues liquid, fixed-rate deposits. The convergence of two independent theories on the same institution suggests the commercial bank is a robust organizational solution to multiple market failures simultaneously.</p>
<hr>
</section>
<section id="diversification-the-unifying-principle" class="level3" data-number="5.3.14">
<h3 data-number="5.3.14" class="anchored" data-anchor-id="diversification-the-unifying-principle"><span class="header-section-number">5.3.14</span> Diversification: The Unifying Principle</h3>
<p>The ex ante and ex post solutions look different on the surface — signaling quality through equity retention versus monitoring borrowers to prevent misreporting — but they rest on exactly the same foundation: <strong>the Law of Large Numbers</strong>. In both cases, a bank that holds many independent loans can perform a costly information function at vanishing per-loan cost as the portfolio grows.</p>
<p>Screening and monitoring are also <strong>complements</strong>: the banking relationship that produces information ex ante (RT) lowers monitoring costs ex post (Diamond). A bank that has already screened a borrower knows their operations and cash flows, observes early warning signs of distress through deposit account data, and can monitor at lower cost than any outside investor starting from scratch. This complementarity explains why both functions are co-located in the same institution rather than performed by separate entities.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Diversification Solves Both Information Problems
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Ex Ante: Screening</th>
<th>Ex Post: Monitoring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Information problem</strong></td>
<td>Cannot observe borrower <em>type</em> before lending</td>
<td>Cannot observe realized <em>return</em> after lending</td>
</tr>
<tr class="even">
<td><strong>Cost without bank</strong></td>
<td>Good borrowers excluded; individual signaling costly</td>
<td>Liquidation waste <span class="math inline">\(S = 0.2\)</span>; delegation cost <span class="math inline">\(D\)</span></td>
</tr>
<tr class="odd">
<td><strong>Bank’s mechanism</strong></td>
<td>Retain portfolio equity; pool screening signals</td>
<td>Monitor borrowers; diversify independent default risk</td>
</tr>
<tr class="even">
<td><strong>LLN result</strong></td>
<td><span class="math inline">\(\text{Var}(\bar{\varepsilon}) = \sigma^2/n \to 0\)</span></td>
<td><span class="math inline">\(D(n) \to 0\)</span> as <span class="math inline">\(n \to \infty\)</span></td>
</tr>
<tr class="odd">
<td><strong>Per-loan cost</strong></td>
<td>Signaling cost <span class="math inline">\(\to 0\)</span></td>
<td>Delegation cost <span class="math inline">\(\to 0\)</span></td>
</tr>
<tr class="even">
<td><strong>Reference</strong></td>
<td>Leland-Pyle (1977), Ramakrishnan-Thakor (1984)</td>
<td>Diamond (1984, 1996)</td>
</tr>
</tbody>
</table>
<p>In both cases: <strong>more loans → less information cost per loan → cheaper deposits → more efficient lending</strong>.</p>
</div>
</div>
<p>Banks are not passive intermediaries that simply channel funds from savers to borrowers. They are <strong>information producers</strong>: institutions that manufacture the information needed to make lending feasible, at a cost that individual investors cannot match. The commercial bank’s organizational form — many loans on the asset side, fixed-rate deposits on the liability side — follows directly from this information production function. Diversification is the technology that makes information production scalable.</p>
<hr>
</section>
</section>
<section id="key-takeaways" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">5.4</span> Key Takeaways</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Main Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Two information problems</strong>: Banks solve two distinct asset-side information problems. Before lending (ex ante): adverse selection prevents lenders from distinguishing good from bad borrowers. After lending (ex post): moral hazard allows borrowers to misreport realized returns. Both problems, left unsolved, either destroy markets or generate costly inefficiencies.</p></li>
<li><p><strong>Market exclusion (Stiglitz-Weiss 1981)</strong>: When lenders cannot observe borrower type, the pooling break-even face value exceeds the good borrower’s participation constraint. Good borrowers are excluded from credit markets entirely. Expected lender return <span class="math inline">\(\Pi(f)\)</span> is non-monotone: the discrete drop at <span class="math inline">\(f = y_G\)</span> (where good types exit) makes pooling unprofitable. The lender breaks even only by lending to bad types at <span class="math inline">\(f_B^* = 2.625\)</span>.</p></li>
<li><p><strong>Certification by signaling (Leland-Pyle 1977)</strong>: Entrepreneurs signal project quality by retaining equity, increasing in <span class="math inline">\(\theta\)</span> (single-crossing). The informed party moves first: costly equity retention is credible because it is more burdensome for low-quality projects. Banks certify portfolio quality to depositors via the same mechanism; diversification drives signaling cost to zero as <span class="math inline">\(n \to \infty\)</span>: <span class="math inline">\(\text{Var}(\bar{\varepsilon}) = \sigma^2/n \to 0\)</span>.</p></li>
<li><p><strong>Information aggregation (Ramakrishnan-Thakor 1984)</strong>: A coalition of <span class="math inline">\(n\)</span> specialists aggregates independent noisy signals into an increasingly precise estimate of portfolio quality. As <span class="math inline">\(n \to \infty\)</span>, residual uncertainty vanishes — the bank can fund deposits near the risk-free rate. Specialization and diversification are complements in information production.</p></li>
<li><p><strong>Relationship banking (Fama 1985)</strong>: Bank loans are “special” because repeated interaction produces private information. A bank credit line certifies borrower quality to outside investors. Screening (ex ante) and monitoring (ex post) are <strong>complements</strong> — established banking relationships reduce both adverse selection and monitoring costs, explaining why both functions co-locate in a single institution.</p></li>
<li><p><strong>The unmonitored debt problem</strong>: Without monitoring, lenders can only enforce repayment through liquidation. Unmonitored debt with face value <span class="math inline">\(f^* = 1.3125\)</span> wastes <span class="math inline">\(S = 0.2\)</span> per borrower (the CSV liquidation cost). Monitoring is socially valuable (<span class="math inline">\(S &gt; K\)</span>) but individually prohibitive when duplicated (<span class="math inline">\(mK = 2 \gg S\)</span>).</p></li>
<li><p><strong>Delegation solves the ex post problem</strong>: A bank monitors on behalf of <span class="math inline">\(m\)</span> depositors, eliminating duplication. Diversification across <span class="math inline">\(n\)</span> independent loans drives delegation cost <span class="math inline">\(D(n) \to 0\)</span> as <span class="math inline">\(n \to \infty\)</span>. Two-loan bank: <span class="math inline">\(K + D = 0.141 &lt; S = 0.2\)</span>. Fully diversified bank: <span class="math inline">\(K + D \to K = 0.0002\)</span>.</p></li>
<li><p><strong>Diversification is the unifying mechanism</strong>: Whether solving the ex ante problem (signaling portfolio quality) or the ex post problem (delegating monitoring), the bank exploits the LLN to drive information costs to zero. Diversification is not just a risk-management tool — it is the core technology that makes the bank a scalable information producer. Fixed-rate deposits minimize depositor monitoring (Gale-Hellwig on both sides), and the bank’s transformation — opaque risky loans <span class="math inline">\(\to\)</span> transparent riskless deposits — rests entirely on this mechanism.</p></li>
</ol>
</div>
</div>
<hr>
</section>
<section id="references" class="level2 appendix" data-number="5.5">
<h2 class="appendix anchored" data-number="5.5" data-anchor-id="references"><span class="header-section-number">5.5</span> References</h2>
<section id="primary-sources" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="primary-sources"><span class="header-section-number">5.5.1</span> Primary Sources</h3>
<ul>
<li><p><strong>Stiglitz, J. E., &amp; Weiss, A. (1981)</strong>. Credit markets with imperfect information. <em>American Economic Review</em>, 71(3), 393–410.</p></li>
<li><p><strong>Leland, H. E., &amp; Pyle, D. H. (1977)</strong>. Informational asymmetries, financial structure, and financial intermediation. <em>Journal of Finance</em>, 32(2), 371–387.</p></li>
<li><p><strong>Ramakrishnan, R. T. S., &amp; Thakor, A. V. (1984)</strong>. Information reliability and a theory of financial intermediation. <em>Review of Economic Studies</em>, 51(3), 415–432.</p></li>
<li><p><strong>Fama, E. F. (1985)</strong>. What’s different about banks? <em>Journal of Monetary Economics</em>, 15(1), 29–39.</p></li>
<li><p><strong>Diamond, D. W. (1984)</strong>. Financial intermediation and delegated monitoring. <em>Review of Economic Studies</em>, 51(3), 393–414.</p></li>
<li><p><strong>Diamond, D. W. (1996)</strong>. Financial intermediation as delegated monitoring: A simple example. <em>Federal Reserve Bank of Richmond Economic Quarterly</em>, 82(3), 51–66.</p></li>
</ul>
</section>
<section id="foundations-debt-and-liquidation" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="foundations-debt-and-liquidation"><span class="header-section-number">5.5.2</span> Foundations: Debt and Liquidation</h3>
<ul>
<li><p><strong>Townsend, R. M. (1979)</strong>. Optimal contracts and competitive markets with costly state verification. <em>Journal of Economic Theory</em>, 21(2), 265–293.</p></li>
<li><p><strong>Gale, D., &amp; Hellwig, M. (1985)</strong>. Incentive-compatible debt contracts: The one-period problem. <em>Review of Economic Studies</em>, 52(4), 647–663.</p></li>
</ul>
</section>
<section id="extensions" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="extensions"><span class="header-section-number">5.5.3</span> Extensions</h3>
<ul>
<li><p><strong>Boyd, J. H., &amp; Prescott, E. C. (1986)</strong>. Financial intermediary-coalitions. <em>Journal of Economic Theory</em>, 38(2), 211–232.</p></li>
<li><p><strong>Williamson, S. D. (1987)</strong>. Costly monitoring, loan contracts, and equilibrium credit rationing. <em>Quarterly Journal of Economics</em>, 102(1), 135–145.</p></li>
<li><p><strong>Krasa, S., &amp; Villamil, A. P. (1992)</strong>. Monitoring the monitor: An incentive structure for a financial intermediary. <em>Journal of Economic Theory</em>, 57(1), 197–221.</p></li>
</ul>
</section>
<section id="integrating-the-liability-and-asset-sides" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="integrating-the-liability-and-asset-sides"><span class="header-section-number">5.5.4</span> Integrating the Liability and Asset Sides</h3>
<ul>
<li><p><strong>Diamond, D. W., &amp; Dybvig, P. H. (1983)</strong>. Bank runs, deposit insurance, and liquidity. <em>Journal of Political Economy</em>, 91(3), 401–419.</p></li>
<li><p><strong>Diamond, D. W., &amp; Rajan, R. G. (2001)</strong>. Liquidity risk, liquidity creation, and financial fragility: A theory of banking. <em>Journal of Political Economy</em>, 109(2), 287–327.</p></li>
</ul>
</section>
<section id="empirical-relevance" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="empirical-relevance"><span class="header-section-number">5.5.5</span> Empirical Relevance</h3>
<ul>
<li><p><strong>Petersen, M. A., &amp; Rajan, R. G. (1994)</strong>. The benefits of lending relationships: Evidence from small business data. <em>Journal of Finance</em>, 49(1), 3–37.</p></li>
<li><p><strong>Berger, A. N., &amp; Udell, G. F. (2002)</strong>. Small business credit availability and relationship lending: The importance of bank organisational structure. <em>Economic Journal</em>, 112(477), F32–F53.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Notes/04_chapter4_supplement.html" class="pagination-link" aria-label="Bank Runs and Failures: Supplement">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bank Runs and Failures: Supplement</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Notes/06_chapter6_liquidity_provision.html" class="pagination-link" aria-label="The Deposit-Lending Synergy">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Deposit-Lending Synergy</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>