<!DOCTYPE html>
<html lang="en"><head>
<script src="05_chapter5_information_producers_files/libs/clipboard/clipboard.min.js"></script>
<script src="05_chapter5_information_producers_files/libs/quarto-html/tabby.min.js"></script>
<script src="05_chapter5_information_producers_files/libs/quarto-html/popper.min.js"></script>
<script src="05_chapter5_information_producers_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="05_chapter5_information_producers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="05_chapter5_information_producers_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="05_chapter5_information_producers_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.40">

  <meta name="author" content="Rajesh Narayanan">
  <title>Lecture 5: Banks as Information Producers</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="05_chapter5_information_producers_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="05_chapter5_information_producers_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="05_chapter5_information_producers_files/libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="05_chapter5_information_producers_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
  .reveal ol, .reveal ul {
    margin-left: 1.5em;
    padding-left: 0.5em;
  }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Lecture 5: Banks as Information Producers</h1>
  <p class="subtitle">The Asset-Side Role of Banks</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rajesh Narayanan 
</div>
        <p class="quarto-title-affiliation">
            LSU Business - Department of Finance
          </p>
    </div>
</div>

  <p class="date">March 2026</p>
</section>
<section>
<section id="overview" class="title-slide slide level1 section center" data-number="1">
<h1><span class="header-section-number">1</span> Overview</h1>

</section>
<section id="learning-objectives" class="slide level2 scrollable" data-number="1.1">
<h2><span class="header-section-number">1.1</span> Learning Objectives</h2>
<p>By the end of this lecture, you should be able to:</p>
<div>
<ol type="1">
<li class="fragment">Explain the two information problems in lending (ex ante and ex post) and why they generate market failures</li>
<li class="fragment">Describe how Stiglitz-Weiss (1981) leads to market exclusion of good borrowers</li>
<li class="fragment">Explain how signaling/certification (Leland-Pyle) and information aggregation (Ramakrishnan-Thakor) address the ex ante problem</li>
<li class="fragment">Work through the Diamond (1996) numerical example: unmonitored debt, monitored debt, and the delegation problem</li>
<li class="fragment">Explain why diversification drives delegation costs to zero (Diamond 1984) and how it unifies the ex ante and ex post solutions</li>
<li class="fragment">Describe the organizational form of the bank as a consequence of these information problems</li>
</ol>
</div>
</section>
<section id="roadmap" class="slide level2 smaller" data-number="1.2">
<h2><span class="header-section-number">1.2</span> Roadmap</h2>
<p><strong>Part 1: The Two Information Problems</strong></p>
<ul>
<li>Asset side vs.&nbsp;liability side; adverse selection vs.&nbsp;moral hazard</li>
</ul>
<p><strong>Part 2: Ex Ante — Banks as Information Producers</strong></p>
<ul>
<li>Stiglitz-Weiss: market exclusion; Leland-Pyle: signaling; Ramakrishnan-Thakor: information production; Fama: certification</li>
</ul>
<p><strong>Part 3: Ex Post — Banks as Delegated Monitors</strong></p>
<ul>
<li>Costly state verification; standard debt (Gale-Hellwig); Diamond (1996) numerical example</li>
</ul>
<p><strong>Part 4: The Delegation Problem and Its Solution</strong></p>
<ul>
<li>Why direct monitoring fails; bank as delegated monitor; one-loan vs.&nbsp;two-loan bank</li>
</ul>
<p><strong>Part 5: Diamond (1984) — The General Model</strong></p>
<ul>
<li>LLN, <span class="math inline">\(D(n) \to 0\)</span>, main theorem, debt optimal on both sides</li>
</ul>
<p><strong>Part 6: Diversification — The Unifying Principle</strong></p>
<ul>
<li>Same LLN logic in ex ante and ex post; what makes a good bank</li>
</ul>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-1-the-two-information-problems" class="title-slide slide level1 section center" data-number="2">
<h1><span class="header-section-number">2</span> Part 1: The Two Information Problems</h1>

</section>
<section id="asset-side-vs.-liability-side" class="slide level2" data-number="2.1">
<h2><span class="header-section-number">2.1</span> Asset Side vs.&nbsp;Liability Side</h2>
<p>Previous lectures: the <strong>liability-side</strong> justification for banking (Diamond-Dybvig 1983)</p>
<ul>
<li>Banks pool liquidity risk → transform illiquid assets into liquid deposits</li>
</ul>
<div class="fragment">
<p>This lecture: the <strong>asset-side</strong> justification (Diamond 1984)</p>
<ul>
<li>Banks resolve information asymmetry between borrowers and lenders</li>
<li>Banks exist even if there were <em>no</em> liquidity problem</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Core Question</strong></p>
</div>
<div class="callout-content">
<p>Who monitors the borrower? And who monitors the monitor?</p>
</div>
</div>
</div>
</div>
</section>
<section id="two-distinct-problems" class="slide level2" data-number="2.2">
<h2><span class="header-section-number">2.2</span> Two Distinct Problems</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Ex Ante</strong></th>
<th><strong>Ex Post</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>When</strong></td>
<td>Before lending</td>
<td>After lending</td>
</tr>
<tr class="even">
<td><strong>Problem</strong></td>
<td>Adverse selection</td>
<td>Moral hazard</td>
</tr>
<tr class="odd">
<td><strong>Cannot observe</strong></td>
<td>Borrower <em>type</em></td>
<td>Realized <em>return</em></td>
</tr>
<tr class="even">
<td><strong>Market failure</strong></td>
<td>Good borrowers excluded</td>
<td>Waste from liquidation</td>
</tr>
<tr class="odd">
<td><strong>Solution</strong></td>
<td>Screening / signaling</td>
<td>Monitoring</td>
</tr>
<tr class="even">
<td><strong>Key paper</strong></td>
<td>Stiglitz-Weiss (1981)</td>
<td>Diamond (1984, 1996)</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Both solved by the same institution — the <strong>commercial bank</strong> — using the same tool: <strong>diversification</strong>.</p>
</div>
</section>
<section id="unified-notation" class="slide level2 smaller" data-number="2.3">
<h2><span class="header-section-number">2.3</span> Unified Notation</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\theta \in \{G, B\}\)</span></td>
<td>Borrower type (good/bad)</td>
<td>Ex ante</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p_\theta\)</span></td>
<td>Success probability; <span class="math inline">\(p_G &gt; p_B\)</span></td>
<td>Ex ante</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(y_\theta\)</span></td>
<td>Payoff if success; <span class="math inline">\(p_G y_G = p_B y_B = \mu\)</span></td>
<td>Ex ante</td>
</tr>
<tr class="even">
<td><span class="math inline">\(f\)</span></td>
<td>Face value of loan</td>
<td>Both</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(f_\theta^*\)</span></td>
<td>Type break-even: <span class="math inline">\(f_\theta^* = r/p_\theta\)</span></td>
<td>Ex ante</td>
</tr>
<tr class="even">
<td><span class="math inline">\(V \in \{H, L\}\)</span></td>
<td>Project return (high/low)</td>
<td>Ex post</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(P = 0.8\)</span>, <span class="math inline">\(H = 1.4\)</span>, <span class="math inline">\(L = 1\)</span></td>
<td>Ex post project parameters</td>
<td>Ex post</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu = 1.32\)</span>, <span class="math inline">\(r = 1.05\)</span></td>
<td>Expected return, risk-free rate</td>
<td>Both</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(K\)</span></td>
<td>Information cost (screening or monitoring)</td>
<td>Both</td>
</tr>
<tr class="even">
<td><span class="math inline">\(S = 0.2\)</span></td>
<td>Liquidation waste</td>
<td>Ex post</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(D(n)\)</span></td>
<td>Delegation cost for <span class="math inline">\(n\)</span>-loan bank</td>
<td>Ex post</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Connection</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(f_G^* = r/p_G = 1.05/0.8 = \mathbf{1.3125}\)</span> — this same number reappears as Diamond’s unmonitored face value <span class="math inline">\(f^*\)</span>.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-2-ex-ante-banks-as-information-producers" class="title-slide slide level1 section center" data-number="3">
<h1><span class="header-section-number">3</span> Part 2: Ex Ante — Banks as Information Producers</h1>

</section>
<section id="the-adverse-selection-setup" class="slide level2" data-number="3.1">
<h2><span class="header-section-number">3.1</span> The Adverse Selection Setup</h2>
<p><strong>Borrowers</strong>: two types <span class="math inline">\(\theta \in \{G, B\}\)</span>, fraction <span class="math inline">\(\alpha = 0.5\)</span> are type <span class="math inline">\(G\)</span></p>
<p><strong>Mean-preserving spread</strong>: <span class="math display">\[p_G &gt; p_B, \quad y_G &lt; y_B, \quad p_G y_G = p_B y_B = \mu = 1.32\]</span></p>
<div class="fragment">
<p><strong>Parameters</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Type <span class="math inline">\(G\)</span></th>
<th>Type <span class="math inline">\(B\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Success prob <span class="math inline">\(p_\theta\)</span></td>
<td>0.8</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>Success payoff <span class="math inline">\(y_\theta\)</span></td>
<td>1.65</td>
<td>3.30</td>
</tr>
<tr class="odd">
<td>Break-even face value <span class="math inline">\(f_\theta^*\)</span></td>
<td><strong>1.3125</strong></td>
<td>2.625</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><strong>Key</strong>: lender cannot observe <span class="math inline">\(\theta\)</span> — only the loan outcome</p>
</div>
</section>
<section id="the-adverse-selection-mechanism" class="slide level2" data-number="3.2">
<h2><span class="header-section-number">3.2</span> The Adverse Selection Mechanism</h2>
<p>A borrower participates only if <span class="math inline">\(f \leq y_\theta\)</span> (non-negative expected profit).</p>
<p>Since <span class="math inline">\(y_G &lt; y_B\)</span>: <strong>good borrowers exit first</strong> as <span class="math inline">\(f\)</span> rises.</p>
<div class="fragment">
<p><strong>The dilemma</strong>:</p>
<ul>
<li>At <span class="math inline">\(f \leq y_G = 1.65\)</span>: both types borrow, but <span class="math inline">\(\Pi(f) = \bar{p} f &lt; r\)</span> always
<ul>
<li><span class="math inline">\(\bar{p} = 0.5(0.8) + 0.5(0.4) = 0.60\)</span>; pooling break-even requires <span class="math inline">\(f^{pool} = 1.75 &gt; y_G\)</span></li>
</ul></li>
<li>At <span class="math inline">\(f &gt; y_G\)</span>: only type <span class="math inline">\(B\)</span> borrows — pool quality collapses</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Proposition (Stiglitz-Weiss 1981)</strong></p>
</div>
<div class="callout-content">
<p>Lender breaks even only at <span class="math inline">\(f_B^* = 2.625\)</span>, lending exclusively to bad borrowers. Good borrowers — who would accept <span class="math inline">\(f_G^* = 1.3125\)</span> — are <strong>excluded entirely</strong>, despite positive-NPV projects (<span class="math inline">\(\mu - r = 0.27 &gt; 0\)</span>).</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-lenders-expected-return" class="slide level2" data-number="3.3">
<h2><span class="header-section-number">3.3</span> The Lender’s Expected Return</h2>
<div style="margin: 10px 0;">
  <svg width="580" height="300" viewbox="0 0 580 300" style="margin: 0 auto; display: block; font-family: serif;">
    <defs>
      <marker id="arrowSW5" markerwidth="10" markerheight="10" refx="9" refy="3" orient="auto">
        <path d="M0,0 L0,6 L9,3 z" fill="#333"></path>
      </marker>
    </defs>
    <line x1="80" y1="250" x2="530" y2="250" stroke="#333" stroke-width="1.5" marker-end="url(#arrowSW5)"></line>
    <line x1="80" y1="255" x2="80" y2="20" stroke="#333" stroke-width="1.5" marker-end="url(#arrowSW5)"></line>
    <text x="540" y="255" font-size="12" fill="#333" font-style="italic">f</text>
    <text x="30" y="22" font-size="11" fill="#333">Π(f)</text>
    <!-- Segment 1: both types, slope pbar=0.60 -->
    <line x1="80" y1="148" x2="177" y2="81" stroke="#1565c0" stroke-width="2.5"></line>
    <!-- Drop at y_G=1.65 -->
    <line x1="177" y1="81" x2="177" y2="137" stroke="#1565c0" stroke-width="2" stroke-dasharray="5,3"></line>
    <!-- Segment 2: only bad type, slope p_B=0.40 -->
    <line x1="177" y1="137" x2="425" y2="18" stroke="#1565c0" stroke-width="2.5"></line>
    <!-- Drop at y_B=3.30 -->
    <line x1="425" y1="18" x2="425" y2="250" stroke="#1565c0" stroke-width="2" stroke-dasharray="5,3"></line>
    <!-- Break-even line r=1.05 -->
    <line x1="80" y1="67" x2="530" y2="67" stroke="#2e7d32" stroke-width="1.5" stroke-dasharray="7,4"></line>
    <text x="420" y="61" font-size="10" fill="#2e7d32" font-weight="bold">r = 1.05</text>
    <!-- f_B* marker -->
    <circle cx="324" cy="67" r="5" fill="#2e7d32"></circle>
    <line x1="324" y1="67" x2="324" y2="250" stroke="#2e7d32" stroke-width="1.2" stroke-dasharray="4,3"></line>
    <text x="324" y="266" font-size="10" fill="#2e7d32" text-anchor="middle">f*_B = 2.625</text>
    <!-- y_G marker -->
    <line x1="177" y1="250" x2="177" y2="255" stroke="#e53935" stroke-width="1.5"></line>
    <text x="177" y="270" font-size="10" fill="#e53935" text-anchor="middle">y_G = 1.65 (good exit)</text>
    <!-- f_G* marker -->
    <line x1="127" y1="250" x2="127" y2="255" stroke="#e65100" stroke-width="1.5"></line>
    <text x="127" y="270" font-size="10" fill="#e65100" text-anchor="middle">f*_G = 1.3125</text>
    <!-- Shaded pooling zone -->
    <rect x="80" y="67" width="97" height="183" fill="#ffebee" fill-opacity="0.5"></rect>
    <text x="129" y="165" font-size="9" fill="#c62828" text-anchor="middle">Pooling: Π &lt; r</text>
    <!-- Slope annotations -->
    <text x="90" y="108" font-size="10" fill="#1565c0">slope = p̄</text>
    <text x="220" y="100" font-size="10" fill="#1565c0">slope = p_B</text>
  </svg>
</div>
<p>At <span class="math inline">\(f = y_G\)</span>: <span class="math inline">\(\Pi\)</span> drops from <span class="math inline">\(0.99\)</span> to <span class="math inline">\(0.66\)</span> — a 33% fall. Both segments lie <strong>below</strong> break-even in the pooling range.</p>
</section>
<section id="signaling-leland-pyle-1977" class="slide level2" data-number="3.4">
<h2><span class="header-section-number">3.4</span> Signaling: Leland-Pyle (1977)</h2>
<p><strong>Idea</strong>: Can high-quality borrowers credibly signal their type?</p>
<p><strong>Signal</strong>: entrepreneur retains equity fraction <span class="math inline">\(e\)</span> in their own project</p>
<div class="fragment">
<p><strong>Why it works</strong> (single-crossing):</p>
<ul>
<li>Retaining equity is <em>costly</em> — entrepreneur bears undiversified risk</li>
<li>Cost is <strong>proportionally lower</strong> for high-quality projects (higher expected return compensates more)</li>
<li>Low-quality borrowers cannot profitably mimic high-quality ones</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Result (Leland-Pyle 1977)</strong></p>
</div>
<div class="callout-content">
<p>In the separating equilibrium, <span class="math inline">\(e^*(\theta)\)</span> is strictly <strong>increasing</strong> in <span class="math inline">\(\theta\)</span>. Market infers type from retention; lenders offer <span class="math inline">\(f_\theta^* = r/p_\theta\)</span>. Adverse selection is eliminated for borrowers who can credibly signal.</p>
<p><strong>Note</strong>: LP applies to individual entrepreneurs. The information originates with the <em>borrower</em>, not the bank.</p>
</div>
</div>
</div>
</div>
</section>
<section id="banks-as-information-producers-ramakrishnan-thakor-1984" class="slide level2" data-number="3.5">
<h2><span class="header-section-number">3.5</span> Banks as Information Producers: Ramakrishnan-Thakor (1984)</h2>
<p><strong>LP applies to individual borrowers</strong>. RT formalize the bank-centric extension: the bank <em>actively produces</em> information by pooling signals from <span class="math inline">\(n\)</span> specialists.</p>
<p>Each screener observes <span class="math inline">\(s_j = \theta_j + \varepsilon_j\)</span> (independent noise). The portfolio average:</p>
<p><span class="math display">\[\bar{s} = \frac{1}{n}\sum_j s_j \quad \Rightarrow \quad \text{estimation error} = \bar{\varepsilon} \sim N\!\left(0, \frac{\sigma^2_\varepsilon}{n}\right) \to 0\]</span></p>
<div class="fragment">
<p>Signaling cost of portfolio quality <span class="math inline">\(\bar{\theta}\)</span> also vanishes: <span class="math inline">\(\frac{A}{2}(e^*)^2 \cdot \frac{\sigma^2}{n} \to 0\)</span></p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Result (Ramakrishnan-Thakor 1984)</strong></p>
</div>
<div class="callout-content">
<p>Coalition of <span class="math inline">\(n\)</span> screeners signals portfolio quality with precision <span class="math inline">\(\to 1\)</span> as <span class="math inline">\(n \to \infty\)</span>. Residual uncertainty vanishes — bank funds deposits near risk-free rate. Specialization (lower <span class="math inline">\(K\)</span> per loan) and diversification (higher precision) are <strong>complements</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="banks-as-certifiers-fama-1985" class="slide level2" data-number="3.6">
<h2><span class="header-section-number">3.6</span> Banks as Certifiers: Fama (1985)</h2>
<p><strong>Observation</strong>: Firms pay a premium for bank loans over bonds — yet value banking relationships</p>
<p><strong>Why?</strong> Banks produce <strong>private information</strong> through the banking relationship:</p>
<ul>
<li>Access to deposit account data → observe cash flows continuously</li>
<li>Repeated interaction → build private knowledge of borrower quality</li>
<li>Screening (ex ante) → lower monitoring costs (ex post)</li>
</ul>
<div class="fragment">
<p><strong>Bank credit line as quality signal</strong>:</p>
<ul>
<li>Obtaining a credit line certifies the firm has passed bank screening</li>
<li>Stock price <strong>rises</strong> on bank credit line announcement</li>
<li>Bond market investors update: <span class="math inline">\(\Pr(\theta = G \mid \text{credit line}) &gt; \alpha\)</span></li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Insight (Fama 1985)</strong></p>
</div>
<div class="callout-content">
<p>Screening and monitoring are <strong>complements</strong> — both co-locate in the bank because the banking relationship reduces costs for both functions simultaneously.</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-3-ex-post-banks-as-delegated-monitors" class="title-slide slide level1 section center" data-number="4">
<h1><span class="header-section-number">4</span> Part 3: Ex Post — Banks as Delegated Monitors</h1>

</section>
<section id="the-ex-post-problem" class="slide level2" data-number="4.1">
<h2><span class="header-section-number">4.1</span> The Ex Post Problem</h2>
<p>After lending, the borrower observes realized return <span class="math inline">\(V\)</span> — the lender does not.</p>
<p><span class="math display">\[V = \begin{cases} H = 1.4 &amp; \text{with prob } P = 0.8 \\ L = 1 &amp; \text{with prob } 1-P = 0.2 \end{cases}\]</span></p>
<p><strong>Expected return</strong>: <span class="math inline">\(\mu = 0.8(1.4) + 0.2(1) = 1.32 &gt; r = 1.05\)</span> ✓</p>
<div class="fragment">
<p><strong>Moral hazard</strong>: borrower can claim <span class="math inline">\(V = 0\)</span> and pocket the proceeds. Any contract based on <em>reported</em> profits fails — the borrower always reports the minimum.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Root Problem</strong></p>
</div>
<div class="callout-content">
<p>The borrower controls the information. Equity contracts collapse. The lender needs either <strong>monitoring</strong> (verify <span class="math inline">\(V\)</span>) or a <strong>fixed payment</strong> (debt) enforced by a liquidation threat.</p>
</div>
</div>
</div>
</div>
</section>
<section id="costly-state-verification-townsend-1979" class="slide level2" data-number="4.2">
<h2><span class="header-section-number">4.2</span> Costly State Verification: Townsend (1979)</h2>
<p><strong>CSV framework</strong>: lender can pay cost <span class="math inline">\(K\)</span> to verify the true return</p>
<p><strong>Contract design problem</strong>: which states to monitor?</p>
<div class="fragment">
<p><strong>Townsend’s key result</strong>: the optimal rule is <strong>deterministic</strong> — monitor in some states with certainty, not others at all. Randomized monitoring (<span class="math inline">\(K\)</span> with probability <span class="math inline">\(\pi &lt; 1\)</span>) is dominated:</p>
<ul>
<li>Requires <em>larger</em> penalties to deter misreporting (since <span class="math inline">\(\pi &lt; 1\)</span> means lower detection probability)</li>
<li>Imposes needless risk on risk-neutral parties</li>
<li>Never strictly helps — any randomized contract can be matched by a deterministic one at weakly lower cost</li>
</ul>
</div>
<div class="fragment">
<p><strong>Which states?</strong> Only where the borrower <em>cannot</em> pay voluntarily — this delivers Gale-Hellwig.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Proposition (Gale-Hellwig 1985): Standard Debt is Optimal</strong></p>
</div>
<div class="callout-content">
<p>Monitor <strong>only in default states</strong> (when borrower cannot pay). The standard debt contract with face value <span class="math inline">\(F\)</span>:</p>
<ul>
<li><strong>Good state</strong> (<span class="math inline">\(V = H \geq F\)</span>): borrower pays <span class="math inline">\(F\)</span> voluntarily — no monitoring</li>
<li><strong>Bad state</strong> (<span class="math inline">\(V = L &lt; F\)</span>): lender monitors, verifies <span class="math inline">\(V = L\)</span>, collects <span class="math inline">\(L\)</span></li>
</ul>
<p>Expected monitoring cost <span class="math inline">\(= (1-P)K = 0.2 \times 0.0002 = 0.00004\)</span> (nearly zero)</p>
</div>
</div>
</div>
</div>
</section>
<section id="diamond-1996-the-simplified-csv-case" class="slide level2" data-number="4.3">
<h2><span class="header-section-number">4.3</span> Diamond (1996): The Simplified CSV Case</h2>
<p><strong>Simplification</strong>: without monitoring, lender’s only tool is <strong>liquidation</strong> — both parties get <strong>0</strong>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>General CSV</th>
<th>Diamond (1996)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bad state, no monitoring</td>
<td>Misreporting equilibrium</td>
<td><strong>Liquidation → 0</strong></td>
</tr>
<tr class="even">
<td>Bad state, with monitoring</td>
<td>Lender verifies, collects <span class="math inline">\(L - K\)</span></td>
<td>Lender accepts <span class="math inline">\(L = 1\)</span></td>
</tr>
<tr class="odd">
<td>Social waste</td>
<td>Incentive distortion</td>
<td><span class="math inline">\(S = (1-P)L = 0.2\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Two benchmark contracts</strong>:</p>
<ul>
<li><strong>Unmonitored debt</strong> (<span class="math inline">\(f^*\)</span>): enforced by liquidation threat; no verification needed</li>
<li><strong>Monitored debt</strong> (<span class="math inline">\(F\)</span>): CSV-optimal; monitor only in default</li>
</ul>
</div>
</section>
<section id="unmonitored-debt-f-1.3125" class="slide level2" data-number="4.4">
<h2><span class="header-section-number">4.4</span> Unmonitored Debt: <span class="math inline">\(f^* = 1.3125\)</span></h2>
<p><strong>Contract</strong>: pay <span class="math inline">\(f\)</span> or face liquidation (→ both get 0)</p>
<p>Borrower pays <span class="math inline">\(f\)</span> if <span class="math inline">\(V = H\)</span> (keeps <span class="math inline">\(H - f &gt; 0\)</span>), defaults if <span class="math inline">\(V = L &lt; f\)</span>.</p>
<p><strong>Lender’s break-even</strong>: <span class="math display">\[P \cdot f + (1-P) \cdot 0 = r \quad \Rightarrow \quad 0.8f = 1.05 \quad \Rightarrow \quad \boxed{f^* = 1.3125}\]</span></p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>State</th>
<th>Prob</th>
<th>Lender gets</th>
<th>Borrower keeps</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H = 1.4\)</span></td>
<td>0.8</td>
<td><strong>1.3125</strong></td>
<td>0.0875</td>
</tr>
<tr class="even">
<td><span class="math inline">\(L = 1\)</span></td>
<td>0.2</td>
<td><strong>0</strong> (liquidated)</td>
<td>0</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><strong>Deadweight cost</strong>: <span class="math inline">\(S = (1-P) \cdot L = 0.2 \times 1 = \mathbf{0.2}\)</span> destroyed per borrower</p>
</div>
</section>
<section id="monitored-debt-f-approx-1.0625" class="slide level2" data-number="4.5">
<h2><span class="header-section-number">4.5</span> Monitored Debt: <span class="math inline">\(F \approx 1.0625\)</span></h2>
<p><strong>Contract</strong>: monitor in bad state; accept <span class="math inline">\(L = 1\)</span> instead of liquidating</p>
<p><strong>Lender’s break-even</strong>: <span class="math display">\[P \cdot F + (1-P)(L - K) = r \quad \Rightarrow \quad 0.8F + 0.2(1 - 0.0002) = 1.05 \quad \Rightarrow \quad F \approx 1.0625\]</span></p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Unmonitored</strong></p>
<ul>
<li>Face value: <span class="math inline">\(f^* = 1.3125\)</span></li>
<li>Loan rate: <strong>31.25%</strong></li>
<li>Borrower surplus: 0.070</li>
<li>Waste: <span class="math inline">\(S = 0.200\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Monitored</strong></p>
<ul>
<li>Face value: <span class="math inline">\(F \approx 1.0625\)</span></li>
<li>Loan rate: <strong>≈ 6.25%</strong></li>
<li>Borrower surplus: 0.270</li>
<li>Waste: ≈ 0</li>
</ul>
</div></div>
</div>
<div class="fragment">
<p>Monitoring captures the full <span class="math inline">\(S = 0.2\)</span> at cost <span class="math inline">\(\approx 0.00004\)</span>. Enormous net gain — if monitoring is organizationally feasible.</p>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-4-the-delegation-problem-and-its-solution" class="title-slide slide level1 section center" data-number="5">
<h1><span class="header-section-number">5</span> Part 4: The Delegation Problem and Its Solution</h1>

</section>
<section id="why-direct-monitoring-fails" class="slide level2" data-number="5.1">
<h2><span class="header-section-number">5.1</span> Why Direct Monitoring Fails</h2>
<p>Borrower needs <span class="math inline">\(m = 10{,}000\)</span> investors, each contributing <span class="math inline">\(0.0001\)</span>.</p>
<div class="fragment">
<p><strong>If all investors monitor independently</strong>: <span class="math display">\[\text{Total cost} = m \times K = 10{,}000 \times 0.0002 = \mathbf{2}\]</span></p>
<p>This exceeds the <strong>entire project return</strong> of 1.32. Monitoring is socially valuable (<span class="math inline">\(S = 0.2 &gt; K = 0.0002\)</span>) but individually prohibitive when duplicated.</p>
</div>
<div class="fragment">
<p><strong>Free-rider problem</strong>: if only one investor monitors, the information is a public good — everyone else free-rides. Monitoring collapses. Only unmonitored debt at <span class="math inline">\(f^* = 1.3125\)</span> survives.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Core Tension</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(S = 0.2 \gg K = 0.0002\)</span> but <span class="math inline">\(S = 0.2 \ll mK = 2\)</span>. Monitoring is individually cheap but collectively ruinous when duplicated. Need: <strong>one entity monitor on behalf of many</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-bank-as-delegated-monitor" class="slide level2 scrollable" data-number="5.2">
<h2><span class="header-section-number">5.2</span> The Bank as Delegated Monitor</h2>
<p><strong>Structure</strong>: bank intermediates between depositors and borrower</p>
<ol type="1">
<li><strong>Depositors</strong> → bank (deposits, promised payment <span class="math inline">\(B\)</span>)</li>
<li><strong>Bank</strong> → borrower (monitors, collects)</li>
<li>Borrower deals only with the bank — not 10,000 investors</li>
</ol>
<div class="fragment">
<p><strong>New problem</strong>: depositors face the same moral hazard with the bank that investors faced with borrowers. The bank observes loan repayments; depositors do not.</p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two-Tier Information Problem</strong></p>
</div>
<div class="callout-content">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Private info</th>
<th>Misrepresentation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investor → Borrower</td>
<td>Borrower knows <span class="math inline">\(V\)</span></td>
<td>Claim <span class="math inline">\(V = 0\)</span></td>
</tr>
<tr class="even">
<td>Depositor → Bank</td>
<td>Bank knows loan income</td>
<td>Claim loans returned little</td>
</tr>
</tbody>
</table>
<p><strong>Diamond’s key insight</strong>: diversification solves the second problem without depositor monitoring.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-one-loan-bank" class="slide level2" data-number="5.3">
<h2><span class="header-section-number">5.3</span> The One-Loan Bank</h2>
<p>Bank monitors one borrower, issues deposits to <span class="math inline">\(m = 10{,}000\)</span> investors.</p>
<p>Bank collects <span class="math inline">\(F\)</span> (success) or <span class="math inline">\(1\)</span> (monitored failure). Depositors need 5% return:</p>
<p><span class="math display">\[P \cdot B = r \quad \Rightarrow \quad 0.8B = 1.05 \quad \Rightarrow \quad B = 1.3125\]</span></p>
<div class="fragment">
<p><strong>Problem</strong>: in the bad state, bank collected <span class="math inline">\(L = 1\)</span> but owes <span class="math inline">\(B = 1.3125\)</span>. Bank <strong>fails</strong> whenever the borrower defaults — probability <span class="math inline">\(1-P = 0.2\)</span>.</p>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>No Efficiency Gain</strong></p>
</div>
<div class="callout-content">
<p>One-loan bank fails 20% of the time — same as direct finance. Delegation provides <strong>zero efficiency gain</strong> without diversification.</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-two-loan-bank" class="slide level2 smaller" data-number="5.4">
<h2><span class="header-section-number">5.4</span> The Two-Loan Bank</h2>
<p>Bank monitors <strong>two</strong> independent borrowers. Bank income:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Outcome</th>
<th>Prob</th>
<th>Bank income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Both succeed</td>
<td><span class="math inline">\(0.64\)</span></td>
<td><span class="math inline">\(2F\)</span></td>
</tr>
<tr class="even">
<td>One succeeds, one fails</td>
<td><span class="math inline">\(0.32\)</span></td>
<td><span class="math inline">\(F + 1\)</span></td>
</tr>
<tr class="odd">
<td>Both fail</td>
<td><span class="math inline">\(0.04\)</span></td>
<td><span class="math inline">\(2\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Set <span class="math inline">\(F = 1.1875\)</span> so that <span class="math inline">\(F + 1 = 2.1875 \geq 2B\)</span>. Depositor break-even:</p>
<p><span class="math display">\[0.96 \times 2B = 2(1.05) \quad \Rightarrow \quad B = 1.09375, \quad 2B = 2.1875\]</span></p>
</div>
<div class="fragment">
<p><strong>Bank fails only when both default</strong>: probability <span class="math inline">\((1-P)^2 = \mathbf{0.04}\)</span> (down from 20%)</p>
<p><strong>Delegation cost</strong>: <span class="math display">\[D = \underbrace{0.04 \times 2}_{\text{distress}} + \underbrace{0.0608}_{\text{control rent}} = 0.1408\]</span> <span class="math display">\[\boxed{K + D = 0.0002 + 0.1408 = 0.141 &lt; S = 0.200} \quad \checkmark\]</span></p>
</div>
</section>
<section id="three-arrangements-compared" class="slide level2" data-number="5.5">
<h2><span class="header-section-number">5.5</span> Three Arrangements Compared</h2>
<div style="margin: 10px 0;">
  <svg width="600" height="230" viewbox="0 0 600 230" style="margin: 0 auto; display: block; font-family: serif;">
    <text x="300" y="16" font-size="12" font-weight="bold" text-anchor="middle">Total Cost per Borrower</text>
    <!-- Option 1 -->
    <rect x="15" y="25" width="175" height="175" rx="6" fill="#fff3e0" stroke="#e65100" stroke-width="2"></rect>
    <text x="103" y="46" font-size="11" font-weight="bold" text-anchor="middle" fill="#bf360c">(1) No Monitoring</text>
    <text x="103" y="62" font-size="10" text-anchor="middle">Unmonitored debt</text>
    <text x="103" y="78" font-size="10" text-anchor="middle">f = 1.3125</text>
    <text x="103" y="106" font-size="16" font-weight="bold" text-anchor="middle" fill="#e65100">Cost = S = 0.2</text>
    <text x="103" y="130" font-size="10" text-anchor="middle">Loan rate = 31.25%</text>
    <text x="103" y="147" font-size="10" text-anchor="middle">Waste S per borrower</text>
    <!-- Option 2 -->
    <rect x="213" y="25" width="175" height="175" rx="6" fill="#fce4ec" stroke="#c62828" stroke-width="2"></rect>
    <text x="301" y="46" font-size="11" font-weight="bold" text-anchor="middle" fill="#b71c1c">(2) Direct Monitoring</text>
    <text x="301" y="62" font-size="10" text-anchor="middle">All m investors monitor</text>
    <text x="301" y="78" font-size="10" text-anchor="middle">f ≈ 1.0625</text>
    <text x="301" y="106" font-size="16" font-weight="bold" text-anchor="middle" fill="#c62828">Cost = mK = 2</text>
    <text x="301" y="130" font-size="10" text-anchor="middle">Exceeds project value!</text>
    <text x="301" y="147" font-size="10" text-anchor="middle">mK = 2 &gt;&gt; S = 0.2</text>
    <!-- Option 3 -->
    <rect x="412" y="25" width="175" height="175" rx="6" fill="#e8f5e9" stroke="#2e7d32" stroke-width="2"></rect>
    <text x="500" y="46" font-size="11" font-weight="bold" text-anchor="middle" fill="#1b5e20">(3) Delegated Monitor</text>
    <text x="500" y="62" font-size="10" text-anchor="middle">Bank monitors (n=2)</text>
    <text x="500" y="78" font-size="10" text-anchor="middle">F = 1.1875, B = 1.09375</text>
    <text x="500" y="106" font-size="16" font-weight="bold" text-anchor="middle" fill="#2e7d32">Cost = 0.141</text>
    <text x="500" y="130" font-size="10" text-anchor="middle">0.141 &lt; S = 0.2 ✓</text>
    <text x="500" y="147" font-size="10" text-anchor="middle">Net gain = 0.059</text>
    <text x="300" y="218" font-size="10" text-anchor="middle" fill="#333" font-style="italic">K + D = 0.141 &lt; S = 0.2 &lt; mK = 2</text>
  </svg>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-5-diamond-1984-the-general-model" class="title-slide slide level1 section center" data-number="6">
<h1><span class="header-section-number">6</span> Part 5: Diamond (1984) — The General Model</h1>

</section>
<section id="setup-n-loan-bank" class="slide level2" data-number="6.1">
<h2><span class="header-section-number">6.1</span> Setup: <span class="math inline">\(n\)</span>-Loan Bank</h2>
<p><strong><span class="math inline">\(n\)</span> borrowers</strong>, i.i.d. returns <span class="math inline">\(V_j \sim G(\cdot)\)</span>, mean <span class="math inline">\(\mu\)</span>, only borrower observes <span class="math inline">\(V_j\)</span>.</p>
<p><strong>Bank’s per-loan income</strong> (Gale-Hellwig CSV contract): <span class="math display">\[R_j = \min(V_j, F) - K \cdot \mathbf{1}(V_j &lt; F)\]</span></p>
<p><strong>Expected per-loan income</strong>: <span class="math inline">\(\rho \equiv \mathbb{E}[R_j] &gt; B\)</span> (strictly above deposit rate)</p>
<div class="fragment">
<p><strong>Bank’s total income</strong>: <span class="math display">\[W_n = \sum_{j=1}^n R_j \quad \xrightarrow{\text{LLN}} \quad n\rho \quad \text{as } n \to \infty\]</span></p>
<p>Since <span class="math inline">\(\rho &gt; B\)</span>: the bank almost surely pays depositors in full as <span class="math inline">\(n\)</span> grows. Bank failure probability <span class="math inline">\(\to 0\)</span>.</p>
</div>
</section>
<section id="main-theorem-diamond-1984" class="slide level2" data-number="6.2">
<h2><span class="header-section-number">6.2</span> Main Theorem (Diamond 1984)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Theorem: Delegation Cost Vanishes with Diversification</strong></p>
</div>
<div class="callout-content">
<p>Let <span class="math inline">\(R_1, R_2, \ldots\)</span> be i.i.d. with mean <span class="math inline">\(\rho\)</span> and variance <span class="math inline">\(\sigma^2 &lt; \infty\)</span>, and <span class="math inline">\(B &lt; \rho\)</span>. Then:</p>
<p><span class="math display">\[\boxed{D(n) \to 0 \quad \text{as } n \to \infty}\]</span></p>
<p><span class="math display">\[K + D(n) \to K \quad \text{as } n \to \infty\]</span></p>
<p>In the limit: deposit rate <span class="math inline">\(\to r\)</span>, loan rate <span class="math inline">\(\to\)</span> CSV-optimal, full surplus <span class="math inline">\(\mu - r - K\)</span> distributed to borrowers and depositors.</p>
</div>
</div>
</div>
</section>
<section id="proof-sketch-chebyshev-bound" class="slide level2" data-number="6.3">
<h2><span class="header-section-number">6.3</span> Proof Sketch: Chebyshev Bound</h2>
<p>Bank fails when <span class="math inline">\(W_n/n &lt; B\)</span>. Apply Chebyshev to the sample mean:</p>
<p><span class="math display">\[\Pr\!\left(\frac{W_n}{n} &lt; B\right) \leq \Pr\!\left(\left|\frac{W_n}{n} - \rho\right| \geq \rho - B\right) \leq \frac{\sigma^2}{n(\rho - B)^2}\]</span></p>
<div class="fragment">
<ul>
<li>Failure probability is <span class="math inline">\(O(1/n)\)</span> — the bank almost never fails</li>
<li>Financial distress cost <span class="math inline">\(\propto\)</span> failure prob <span class="math inline">\(\to 0\)</span></li>
<li>Control rent needed <span class="math inline">\(\propto\)</span> failure prob <span class="math inline">\(\to 0\)</span></li>
<li>Both components of <span class="math inline">\(D(n)\)</span> are <span class="math inline">\(O(1/n) \to 0\)</span> <span class="math inline">\(\square\)</span></li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Binary Special Case</strong></p>
</div>
<div class="callout-content">
<p>For <span class="math inline">\(n=2\)</span>: exact failure prob <span class="math inline">\(= (1-P)^2 = 0.04\)</span>. Chebyshev gives a conservative upper bound. As <span class="math inline">\(n \to \infty\)</span>: failure prob <span class="math inline">\(\to 0\)</span> geometrically.</p>
</div>
</div>
</div>
</div>
</section>
<section id="debt-is-optimal-on-both-sides" class="slide level2" data-number="6.4">
<h2><span class="header-section-number">6.4</span> Debt is Optimal on Both Sides</h2>
<p>The same CSV logic (Gale-Hellwig) applies twice:</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Relationship</th>
<th>CSV problem</th>
<th>Optimal contract</th>
<th>Monitoring when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bank → Borrower</strong></td>
<td>Borrower hides <span class="math inline">\(V_j\)</span></td>
<td>Loan at face <span class="math inline">\(F\)</span>; monitor in default</td>
<td><span class="math inline">\(V_j &lt; F\)</span>; prob <span class="math inline">\(\approx 0.2\)</span></td>
</tr>
<tr class="even">
<td><strong>Depositor → Bank</strong></td>
<td>Bank hides <span class="math inline">\(W_n\)</span></td>
<td>Deposit at face <span class="math inline">\(B\)</span>; liquidate on failure</td>
<td><span class="math inline">\(W_n &lt; nB\)</span>; prob <span class="math inline">\(O(1/n) \to 0\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Transformation the Bank Performs</strong></p>
</div>
<div class="callout-content">
<p><span class="math display">\[\underbrace{\text{Monitored loans}}_{\text{risky, individually}} \xrightarrow{\;\text{diversification}\;} \underbrace{\text{Fixed-rate deposits}}_{\text{nearly riskless}}\]</span></p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="part-6-diversification-the-unifying-principle" class="title-slide slide level1 section center" data-number="7">
<h1><span class="header-section-number">7</span> Part 6: Diversification — The Unifying Principle</h1>

</section>
<section id="the-same-lln-in-both-settings" class="slide level2" data-number="7.1">
<h2><span class="header-section-number">7.1</span> The Same LLN in Both Settings</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Ex Ante: Screening</th>
<th>Ex Post: Monitoring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Problem</strong></td>
<td>Cannot observe <em>type</em></td>
<td>Cannot observe <em>return</em></td>
</tr>
<tr class="even">
<td><strong>Cost without bank</strong></td>
<td>Market exclusion; signaling costly</td>
<td>Waste <span class="math inline">\(S = 0.2\)</span>; delegation cost <span class="math inline">\(D\)</span></td>
</tr>
<tr class="odd">
<td><strong>Bank’s tool</strong></td>
<td>Diversify signal noise</td>
<td>Diversify default risk</td>
</tr>
<tr class="even">
<td><strong>LLN result</strong></td>
<td><span class="math inline">\(\text{Var}(\bar{\varepsilon}) = \sigma^2/n \to 0\)</span></td>
<td><span class="math inline">\(D(n) \to 0\)</span></td>
</tr>
<tr class="odd">
<td><strong>Outcome</strong></td>
<td>Screening cost <span class="math inline">\(\to 0\)</span></td>
<td>Delegation cost <span class="math inline">\(\to 0\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>One principle, two applications</strong>: diversification makes the bank a scalable information producer — on both sides of the lending relationship.</p>
</div>
</section>
<section id="the-dn-curve" class="slide level2" data-number="7.2">
<h2><span class="header-section-number">7.2</span> The <span class="math inline">\(D(n)\)</span> Curve</h2>
<div style="margin: 10px 0;">
  <svg width="540" height="270" viewbox="0 0 540 270" style="margin: 0 auto; display: block; font-family: serif;">
    <defs>
      <marker id="arr5" markerwidth="10" markerheight="10" refx="9" refy="3" orient="auto">
        <path d="M0,0 L0,6 L9,3 z" fill="black"></path>
      </marker>
    </defs>
    <line x1="60" y1="225" x2="500" y2="225" stroke="black" stroke-width="1.5" marker-end="url(#arr5)"></line>
    <text x="510" y="230" font-size="12" font-style="italic">n</text>
    <line x1="60" y1="235" x2="60" y2="20" stroke="black" stroke-width="1.5" marker-end="url(#arr5)"></line>
    <text x="10" y="130" font-size="10" text-anchor="middle" transform="rotate(-90 10 130)">Cost / borrower</text>
    <!-- Y labels -->
    <line x1="55" y1="45" x2="65" y2="45" stroke="black" stroke-width="1"></line>
    <text x="50" y="49" font-size="10" text-anchor="end">2.0</text>
    <line x1="55" y1="105" x2="65" y2="105" stroke="black" stroke-width="1"></line>
    <text x="50" y="109" font-size="10" text-anchor="end">0.2</text>
    <line x1="55" y1="138" x2="65" y2="138" stroke="black" stroke-width="1"></line>
    <text x="50" y="142" font-size="10" text-anchor="end">0.14</text>
    <line x1="55" y1="221" x2="65" y2="221" stroke="black" stroke-width="1"></line>
    <text x="50" y="225" font-size="10" text-anchor="end">≈0</text>
    <!-- x labels -->
    <line x1="90" y1="220" x2="90" y2="230" stroke="black" stroke-width="1"></line>
    <text x="90" y="244" font-size="10" text-anchor="middle">1</text>
    <line x1="135" y1="220" x2="135" y2="230" stroke="black" stroke-width="1"></line>
    <text x="135" y="244" font-size="10" text-anchor="middle">2</text>
    <!-- mK line -->
    <line x1="60" y1="45" x2="490" y2="45" stroke="red" stroke-width="1.5" stroke-dasharray="8,4"></line>
    <text x="410" y="38" font-size="10" fill="red" font-weight="bold">Direct: mK = 2</text>
    <!-- S line -->
    <line x1="60" y1="105" x2="490" y2="105" stroke="#e65100" stroke-width="1.5" stroke-dasharray="6,3"></line>
    <text x="380" y="98" font-size="10" fill="#e65100" font-weight="bold">No monitoring: S = 0.2</text>
    <!-- K+D(n) curve -->
    <polyline points="90,105 115,115 135,124 160,133 195,143 230,152 270,160 315,167 360,174 405,179 450,183 480,186" fill="none" stroke="#ff8800" stroke-width="2.5"></polyline>
    <!-- n=1 point -->
    <circle cx="90" cy="105" r="4" fill="#888"></circle>
    <!-- n=2 point -->
    <circle cx="135" cy="124" r="5" fill="#ff8800"></circle>
    <text x="154" y="121" font-size="10" fill="#cc6600" font-weight="bold">n=2: K+D = 0.141</text>
    <!-- Asymptote K≈0 -->
    <line x1="60" y1="221" x2="490" y2="221" stroke="green" stroke-width="1.5" stroke-dasharray="5,3"></line>
    <text x="330" y="215" font-size="10" fill="green" font-weight="bold">→ K ≈ 0 as n→∞</text>
    <!-- Curve label -->
    <text x="330" y="163" font-size="11" fill="#cc6600" font-weight="bold">K + D(n)</text>
    <!-- Shaded region -->
    <rect x="60" y="183" width="430" height="38" fill="green" fill-opacity="0.08"></rect>
    <text x="270" y="206" font-size="9" text-anchor="middle" fill="#2e7d32">Delegation beats no monitoring: K + D &lt; S</text>
  </svg>
</div>
</section>
<section id="what-makes-a-good-bank" class="slide level2 smaller" data-number="7.3">
<h2><span class="header-section-number">7.3</span> What Makes a Good Bank?</h2>
<p><strong>Diversification is essential, not optional</strong>:</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Bank type</th>
<th>Failure prob</th>
<th>Delegation cost</th>
<th>Deposit rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Undiversified (<span class="math inline">\(n\)</span> small)</td>
<td>High</td>
<td>High</td>
<td>Above risk-free</td>
</tr>
<tr class="even">
<td>Well-diversified (<span class="math inline">\(n\)</span> large)</td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td><span class="math inline">\(\approx 0\)</span></td>
<td><span class="math inline">\(\approx r\)</span></td>
</tr>
<tr class="odd">
<td>Fully diversified (<span class="math inline">\(n \to \infty\)</span>)</td>
<td>0</td>
<td>0</td>
<td><span class="math inline">\(r\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Policy implications</strong>:</p>
<ul>
<li><strong>Concentration limits</strong>: undiversification is not just risky — it is <em>expensive</em></li>
<li><strong>Hedge non-monitoring risks</strong>: interest rate risk raises distress prob → raises <span class="math inline">\(D(n)\)</span> (Silicon Valley Bank 2023)</li>
<li><strong>Correlated defaults</strong>: if loans are correlated, LLN fails → <span class="math inline">\(D(n)\)</span> stays positive → systemic risk</li>
</ul>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Diamond (1996)</strong></p>
</div>
<div class="callout-content">
<p>“Diversification makes bank deposits much safer than bank loans, and in the limit of fully diversified banks with independently distributed loans, bank deposits become riskless.”</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-full-picture-asset-liability-sides" class="slide level2" data-number="7.4">
<h2><span class="header-section-number">7.4</span> The Full Picture: Asset + Liability Sides</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Liability side (DD 1983)</th>
<th>Asset side (Diamond 1984)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Core problem</strong></td>
<td>Timing / liquidity</td>
<td>Borrower moral hazard</td>
</tr>
<tr class="even">
<td><strong>Bank’s role</strong></td>
<td>Liquidity transformation</td>
<td>Delegated monitoring</td>
</tr>
<tr class="odd">
<td><strong>Mechanism</strong></td>
<td>Pool liquidity shocks</td>
<td>Diversify default risk</td>
</tr>
<tr class="even">
<td><strong>Why debt</strong></td>
<td>Optimal with sequential service</td>
<td>Minimizes depositor monitoring</td>
</tr>
<tr class="odd">
<td><strong>Why many loans</strong></td>
<td>Less relevant</td>
<td>Essential: LLN reduces <span class="math inline">\(D(n)\)</span></td>
</tr>
<tr class="even">
<td><strong>Fragility</strong></td>
<td>Coordination failure / runs</td>
<td>Correlated losses / undiversification</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Both theories independently predict: <strong>many loans, fixed-rate deposits, diversified portfolios</strong>.</p>
<p>The commercial bank is a robust solution to <em>multiple</em> market failures simultaneously.</p>
</div>
</section>
<section id="key-takeaways" class="slide level2 scrollable" data-number="7.5">
<h2><span class="header-section-number">7.5</span> Key Takeaways</h2>
<div>
<ol type="1">
<li class="fragment"><p><strong>Two information problems</strong>: ex ante (adverse selection, type unknown) and ex post (moral hazard, return unverifiable) — both generate market failures without intermediation</p></li>
<li class="fragment"><p><strong>Market exclusion</strong> (Stiglitz-Weiss): pooling rate exceeds good-borrower participation constraint → good borrowers excluded despite positive NPV</p></li>
<li class="fragment"><p><strong>Signaling</strong> (Leland-Pyle): equity retention screens types; banks reduce signaling cost via diversification (<span class="math inline">\(\sigma^2/n \to 0\)</span>)</p></li>
<li class="fragment"><p><strong>Delegated monitoring</strong> (Diamond): bank monitors on behalf of <span class="math inline">\(m\)</span> investors; diversification drives <span class="math inline">\(D(n) \to 0\)</span> — deposits become nearly riskless</p></li>
<li class="fragment"><p><strong>Unifying principle</strong>: the Law of Large Numbers makes banks efficient information producers in <em>both</em> the ex ante and ex post dimensions — more loans → lower information cost per loan → cheaper deposits</p></li>
<li class="fragment"><p><strong>Debt is optimal on both sides</strong>: Gale-Hellwig applies to bank-borrower relationship (loans) and depositor-bank relationship (deposits) — same logic, same contract form</p></li>
</ol>
</div>
</section>
<section id="references" class="slide level2 smaller" data-number="7.6">
<h2><span class="header-section-number">7.6</span> References</h2>
<p><strong>Primary</strong>:</p>
<ul>
<li>Stiglitz, J. E., &amp; Weiss, A. (1981). Credit markets with imperfect information. <em>AER</em>, 71(3).</li>
<li>Leland, H. E., &amp; Pyle, D. H. (1977). Informational asymmetries, financial structure, and financial intermediation. <em>JF</em>, 32(2).</li>
<li>Ramakrishnan, R. T. S., &amp; Thakor, A. V. (1984). Information reliability and a theory of financial intermediation. <em>RES</em>, 51(3).</li>
<li>Fama, E. F. (1985). What’s different about banks? <em>JME</em>, 15(1).</li>
<li>Diamond, D. W. (1984). Financial intermediation and delegated monitoring. <em>RES</em>, 51(3).</li>
<li>Diamond, D. W. (1996). Financial intermediation as delegated monitoring. <em>FRB Richmond EQ</em>, 82(3).</li>
</ul>
<p><strong>Foundations</strong>:</p>
<ul>
<li>Townsend, R. M. (1979). Optimal contracts and competitive markets with costly state verification. <em>JET</em>, 21(2).</li>
<li>Gale, D., &amp; Hellwig, M. (1985). Incentive-compatible debt contracts. <em>RES</em>, 52(4).</li>
<li>Diamond, D. W., &amp; Dybvig, P. H. (1983). Bank runs, deposit insurance, and liquidity. <em>JPE</em>, 91(3).</li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>FIN 7650 Banking - Lecture 5</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="05_chapter5_information_producers_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>